### ISSUE TITLE
Crash for type specifier without space

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#118]
I'm documenting this code:

	/**
	@param{string} x
	*/
	function f(x) {}

And I get an error like this:

	error: could not process the following code.
	/home/andy/git/esdoc/src/file.js
	0| /**
	1| @param{string} x
	2| */
	3| function f(x) {}

	/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:405
	            throw _iteratorError5;
	            ^

	TypeError: Cannot read property 'charAt' of undefined
	    at Function.parse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Parser/CommentParser.js:60:23)
	    at DocFactory._traverseComments (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:545:57)
	    at DocFactory.push (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:436:26)
	    at Controller.<anonymous> (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:439:19)
	    at Controller.enter (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Util/ASTUtil.js:57:20)
	    at Controller.__execute (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:397:31)
	    at Controller.traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:495:28)
	    at Object.traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:707:27)
	    at Function.traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Util/ASTUtil.js:55:31)
	    at Function._traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:437:34)

The problem with the documentation is that it should be `@param {string}` and not `@param{string}`.
But given that this is likely a common error, maybe the error message could be more friendly?

**Comment by h13i32maru** [comment]
@andy-hanson Friendly error message is good. However the implementation is very difficult. So I do not take it.
