### ISSUE TITLE
Crash for `export let`

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#126]
I'm documenting this code:

	export let x

I get this error:

	/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:405
		throw _iteratorError5;
		^
	TypeError: Cannot read property 'type' of null
		at DocFactory._inspectExportNamedDeclaration (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:285:37)
		at new DocFactory (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:92:10)
		at Function._traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:435:21)
		at /home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:183:26
		at Function._walk (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:390:13)
		at Function.generate (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:125:12)
		at ESDocCLI.exec (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDocCLI.js:88:28)
		at Object.<anonymous> (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDocCLI.js:146:7)
		at Module._compile (module.js:435:26)
		at Object.Module._extensions..js (module.js:442:10)

`esdoc --version` is 0.4.1.

**Comment by h13i32maru** [comment]
This is ESDoc's bug. Thanks.

**Comment by h13i32maru** [comment]
I fixed this issue at v0.4.2.
