### ISSUE TITLE
Crash for parameter with type and link and parentheses

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#129]
Probably related to #119.

I'm documenting this code:

	/** @param {boolean} x A parameter (where {@link foo} is its function). */
	export function foo(x) {}

And I get this error:

	SyntaxError: Invalid regular expression: /[~]\boolean} x A parameter (where {@link foo$/: Unterminated group
		at RegExp (native)
		at new RegExp (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/core-js/modules/es6.regexp.js:22:11)
		at IdentifiersDocBuilder._findByName (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:140:20)
		at IdentifiersDocBuilder._buildDocLinkHTML (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:996:22)
		at IdentifiersDocBuilder._buildTypeDocLinkHTML (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:972:21)
		at IdentifiersDocBuilder._buildSignatureHTML (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:1105:33)
		at /home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:498:38
		at IceCap.loop (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:319:15)
		at IdentifiersDocBuilder._buildSummaryDoc (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:495:11)
		at IdentifiersDocBuilder._buildSummaryHTML (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:454:29)

The problem goes away if I remove any one of the type or the link or the parentheses.

**Comment by h13i32maru** [comment]
@andy-hanson This is ESDoc bug. Thanks.

**Comment by h13i32maru** [comment]
I fixed this issue at v0.4.2.
