### ISSUE TITLE
Crashes for '@-'

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#131]
I'm documenting this code:

	/** @- */
	export function foo() {}

It gives this error:

	error: could not process the following code.
	/home/andy/git/ESDOC/src/file.js
	0| /** @- */
	1| export function foo() {}

	/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:405
		throw _iteratorError5;
		^

	TypeError: Cannot read property 'charAt' of undefined
		at Function.parse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Parser/CommentParser.js:60:23)
		at DocFactory._traverseComments (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:546:57)
		at DocFactory.push (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:436:26)
		at Controller.<anonymous> (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:439:19)
		at Controller.enter (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Util/ASTUtil.js:57:20)
		at Controller.__execute (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:397:31)
		at Controller.traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:495:28)
		at Object.traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:707:27)
		at Function.traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Util/ASTUtil.js:55:31)
		at Function._traverse (/home/andy/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/ESDoc.js:437:34)

**Comment by h13i32maru** [comment]
``@-`` is invalid syntax for ESDoc. So, this is valid exception.
