### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by doug-wade** [esdoc/esdoc#132]
I'm trying to use gulp-esdoc to generate my docs, but I've been having some difficulty.  While trying to debug it, I've been getting some rather cryptic errors from ESDoc.generate() -- an AssertionError that undefined == true -- which don't help me much.  What I'd like to see is "source is not defined.  Please provide a source in your config" or something.

Here's the actual stack trace:

```
» gulp docs
[21:52:46] Using gulpfile ~/workplace/yodel/gulpfile.js
[21:52:46] Starting 'docs'...
[21:52:46] Finished 'docs' after 6.57 ms

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: undefined == true
  at Function.generate (/home/doug/workplace/yodel/node_modules/gulp-esdoc/node_modules/esdoc/out/src/ESDoc.js:92:31)
  at DestroyableTransform.flush [as _flush] (/home/doug/workplace/yodel/node_modules/gulp-esdoc/index.js:31:11)
  at DestroyableTransform.<anonymous> (/home/doug/workplace/yodel/node_modules/gulp-esdoc/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:12)
  at DestroyableTransform.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:166:7)
  at prefinish (/home/doug/workplace/yodel/node_modules/gulp-esdoc/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:492:12)
  at finishMaybe (/home/doug/workplace/yodel/node_modules/gulp-esdoc/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:500:7)
  at endWritable (/home/doug/workplace/yodel/node_modules/gulp-esdoc/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:512:3)
  at DestroyableTransform.Writable.end (/home/doug/workplace/yodel/node_modules/gulp-esdoc/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:477:5)
  at DestroyableTransform.onend (/home/doug/workplace/yodel/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
  at DestroyableTransform.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at DestroyableTransform.emit (events.js:166:7)
  at /home/doug/workplace/yodel/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at doNTCallback0 (node.js:407:9)
  at process._tickCallback (node.js:336:13)
```

**Comment by h13i32maru** [comment]
@prekolna Thanks for this suggestion. I consider this.

**Comment by h13i32maru** [comment]
Please check the latest ESDoc. If is problem, please write new issue.
