### ISSUE TITLE
ManualDocBuilder Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by crucialfelix** [esdoc/esdoc#190]
With a very simple manual:

```
{
  "source": "./src",
  "destination": "./esdoc",
  "manual": {
    "changelog": "./docs/CHANGELOG.md"
  }
}
```

Throws this error:

```
/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:339
              throw _iteratorError;
              ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (evalmachine.<anonymous>:603:19)
    at Object.fs.readSync (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:245:23)
    at Object.fs.readFileSync (evalmachine.<anonymous>:438:24)
    at ManualDocBuilder._convertMDToHTML (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/ManualDocBuilder.js:277:46)
    at /Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/ManualDocBuilder.js:212:30
    at /Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/ManualDocBuilder.js:228:13
    at IceCap.loop (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:319:15)
    at ManualDocBuilder._buildManualIndex (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/ManualDocBuilder.js:199:11)
    at ManualDocBuilder.exec (/Users/crucial/.nvm/versions/node/v4.2.1/lib/node_modules/esdoc/out/src/Publisher/Builder/ManualDocBuilder.js:67:14)
```

**Comment by crucialfelix** [comment]
It got this far:

```
esdoc ❯ ll manual
total 8
drwxr-xr-x   3 crucial  staff   102B Dec  4 10:49 .
drwxr-xr-x  18 crucial  staff   612B Dec  4 10:49 ..
-rw-r--r--   1 crucial  staff   2.8K Dec  4 10:49 index.html
```

**Comment by jamsyoung** [comment]
I had the same problem, I had to remove the "manual" node to get it working again.  I haven't looked at the code, but trying to read the CHANGELOG.md, that did exist, is what was causing the problem for me.

**Comment by jamsyoung** [comment]
Reading though the updated docs, looks like the format changed at some point.  If "changelog" is an array, it works.

```json
    "manual": {
        "changelog": ["./CHANGELOG.md"]
    }
```

**Comment by h13i32maru** [comment]
@crucialfelix ``changelog`` requires array.

@jamsyoung Thanks for replying!
