### ISSUE TITLE
Error when using export new instance

### ISSUE THREAD

**Issue by NullDivision** [esdoc/esdoc#207]
Given I have the following code:

``` javascript
export default new winston.Logger({
  transports: [
    new winston.transports.File({filename: path.join(logsPath, 'server.log')})
  ]
});
```

ESDoc fails with:

```
/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/ESDoc.js:409
            throw _iteratorError5;
            ^

TypeError: Cannot read property 'replace' of undefined
    at DocFactory._inspectExportDefaultDeclaration (/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/Factory/DocFactory.js:170:51)
    at new DocFactory (/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/Factory/DocFactory.js:101:10)
    at Function._traverse (/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/ESDoc.js:439:21)
    at /home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/ESDoc.js:187:26
    at Function._walk (/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/ESDoc.js:394:13)
    at Function.generate (/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/ESDoc.js:127:12)
    at ESDocCLI.exec (/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/ESDocCLI.js:90:28)
    at Object.<anonymous> (/home/NullDivision/Projects/MyProject/server/node_modules/esdoc/out/src/ESDocCLI.js:146:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by h13i32maru** [comment]
ESDoc 0.4.4 does not raise this error. However, it is not showed in documentation. I consider this issue.
