### ISSUE TITLE
Maximum call stack error...

### ISSUE THREAD

**Issue by urosjarc** [esdoc/esdoc#217]
Why I get this error while in comand line esdoc every thing is fine...
```
/home/urosjarc/GITHUB/facility_redesign/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:94
            throw _iteratorError;
            ^

RangeError: Maximum call stack size exceeded
    at String (native)
    at RegExp.<anonymous> (/home/urosjarc/GITHUB/facility_redesign/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
    at RegExp.toString (/home/urosjarc/GITHUB/facility_redesign/node_modules/karma/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
    at String (native)
    at RegExp.<anonymous> (/home/urosjarc/GITHUB/facility_redesign/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
    at RegExp.toString (/home/urosjarc/GITHUB/facility_redesign/node_modules/karma/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
    at String (native)
    at RegExp.<anonymous> (/home/urosjarc/GITHUB/facility_redesign/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
    at RegExp.toString (/home/urosjarc/GITHUB/facility_redesign/node_modules/karma/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
    at String (native)
    at RegExp.<anonymous> (/home/urosjarc/GITHUB/facility_redesign/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
    at RegExp.toString (/home/urosjarc/GITHUB/facility_redesign/node_modules/karma/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
    at String (native)
    at RegExp.<anonymous> (/home/urosjarc/GITHUB/facility_redesign/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
    at RegExp.toString (/home/urosjarc/GITHUB/facility_redesign/node_modules/karma/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
    at String (native)
```

**Comment by arcticShadow** [comment]
Hi @urosjarc I notice you have closed this issue. Did you find a solution to the Call stack size issue?

**Comment by urosjarc** [comment]
Yea It was problem with my gulp process not in esdoc lib.

**Comment by fixpunkt** [comment]
@urosjarc can you go into detail about what caused this? I'm hitting the same issue after upgrading my npm dependencies.

**Comment by urosjarc** [comment]
@fixpunkt I have seen this [github issue](https://github.com/google/web-starter-kit/issues/649) that points for to much RAM consumptions. So I played with my `gulp build` task stack and eliminate one task in stack at the time and at the end only `gulp docs` was a cause of my problems.

This was producing my error
```
var esdoc = require("gulp-esdoc");
var esdocConfig = require('../esdoc.json');

gulp.task('docs', function(){ 	
	gulp.src("")
		.pipe(esdoc(esdocConfig));
});
```

I really didn't know why, so I was quesing that require functions makes to much load for gulp to handle, so I moved them in to the task function so they can be loaded only when task is executed.
```

gulp.task('docs',function () {

	var esdoc = require("gulp-esdoc");
	var esdocConfig = require('../esdoc.json');

	gulp.src("")
		.pipe(esdoc(esdocConfig));
});
```

**Comment by fixpunkt** [comment]
Thanks for the hint, moving `require("gulp-esdoc")` actually did fix the problem for me.

However, I don't think this is a RAM exhaustion issue. To me, this looks more like an infinite recursion issue. If you look at your stack trace, you can see that the recursion takes place between a native method and two methods from different installations of `core-js`. I see the same thing:

    RangeError: Maximum call stack size exceeded
        at RegExp.toString (${my_project}/node_modules/core-js/modules/es6.regexp.to-string.js:18:18)
        at String (native)
        at RegExp.<anonymous> (${my_project}/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
        at RegExp.toString (${my_project}/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
        at String (native)
        at RegExp.<anonymous> (${my_project}/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
        at RegExp.toString (${my_project}/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
        at String (native)
        at RegExp.<anonymous> (${my_project}/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
        at RegExp.toString (${my_project}/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
        at String (native)
        at RegExp.<anonymous> (${my_project}/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
        at RegExp.toString (${my_project}/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
        at String (native)
        at RegExp.<anonymous> (${my_project}/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
        at RegExp.toString (${my_project}/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)

In the root of my `node_modules`, I've got `core-js@2.1.0`, while esdoc has `core-js@0.9.18`. I think the issue we're seeing might be caused by two different versions of the polyfill interacting with each other.

I'm not sure whether this is a bug in esdoc or in one of the other packages that are involved.

@h13i32maru should this be reopened or should we open an issue somewhere else?

**Comment by urosjarc** [comment]
Thats great that you have solved issue... I'm quite happy that I have contribute to solving your issue. I really don't have time to debug this issue I joust want that **THING** works. Anyway :+1: for solving your issue.

**Comment by Robinfr** [comment]
+1 I was having the exact same issue. It showed up initially as a Karma issue. It's a bit weird that you have to more the require inside tho..

**Comment by arcticShadow** [comment]
Karma? Yes that's what brought me here. Let's exchange notes.
On Sat, 27 Feb 2016 at 12:04 AM Robin <notifications@github.com> wrote:

> +1 I was having the exact same issue. It showed up initially as a Karma
> issue. It's a bit weird that you have to more the require inside tho..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/esdoc/esdoc/issues/217#issuecomment-189222756>.
>
-- 
Kind Regards,
Cole Diffin

**Comment by Robinfr** [comment]
@arcticShadow well, as was said in here. Moving the require calls inside the task works. For some reason the combination of `require('karma')` and `require('gulp-esdoc')` was causing a stack size error. That's all I really know.

**Comment by arcticShadow** [comment]
A bit of background that I have, karma recently published an update, that
changed the core-Js dependency. I'm not on my computer right now, so i
don't have the exact versions. But off the top of my head core is 2.0.x
works, but 2.1.x doesn't. And to keep the older core Js I have fixed my
karma and Core Js to older versions. However, I would like to keep up to
date it new versions, so would like to help tracking down the issue
On Sat, 27 Feb 2016 at 12:46 AM Robin <notifications@github.com> wrote:

> @arcticShadow <https://github.com/arcticShadow> well, as was said in
> here. Moving the require calls inside the task works. For some reason the
> combination of require('karma') and require('gulp-esdoc') was causing a
> stack size error. That's all I really know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/esdoc/esdoc/issues/217#issuecomment-189237573>.
>
-- 
Kind Regards,
Cole Diffin

**Comment by Robinfr** [comment]
Here are all the commits that happened between 2.0.x and 2.1.x. Check it out https://github.com/zloirock/core-js/compare/v2.0.3...v2.1.0
