### ISSUE TITLE
Function type throws error

### ISSUE THREAD

**Issue by neothemachine** [esdoc/esdoc#228]
With `@return {function(foo, bar)}` I get the following error:

```
..\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:440
            throw _iteratorError2;
            ^

TypeError: Cannot read property 'replace' of undefined
    at ..\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:881:34
    at Array.map (native)
    at IdentifiersDocBuilder._buildTypeDocLinkHTML (..\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:876:41)
    at IdentifiersDocBuilder._buildSignatureHTML (..\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:1122:40)
    at ..\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:469:38
    at IceCap.loop (..\node_modules\esdoc\node_modules\ice-cap\out\src\IceCap.js:319:15)
    at IdentifiersDocBuilder._buildSummaryDoc (..\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:466:11)
    at IdentifiersDocBuilder._buildSummaryHTML (..\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:425:29)
    at IdentifiersDocBuilder._buildIdentifierDoc (..\node_modules\esdoc\out\src\Publisher\Builder\IdentifiersDocBuilder.js:77:40)
    at IdentifiersDocBuilder.exec (..\node_modules\esdoc\out\src\Publisher\Builder\IdentifiersDocBuilder.js:52:32)
```

**Comment by h13i32maru** [comment]
Write variable type ``@return {function(foo:number, bar:string)}``

**Comment by neothemachine** [comment]
Well, it still shouldn't throw a type error, even if the syntax is wrong :)
