### ISSUE TITLE
Error parsing object rest syntax in function argument

### ISSUE THREAD

**Issue by compact** [esdoc/esdoc#253]
ESDoc v0.4.6 is failing to parse a function with an argument that is an object using the rest syntax. I am using esdoc-es7-plugin v0.0.3 as well.

```
export default function example({
    arg1,
    arg2,
    ...otherArgs
}) {
    return;
}
```

```
error: could not process the following code.

-1| undefined
0| export default function example({

node_modules/esdoc/out/src/ESDoc.js:409
            throw _iteratorError5;
            ^

TypeError: Cannot read property 'name' of undefined
    at Function.guessParams (node_modules/esdoc/out/src/Parser/ParamParser.js:352:54)
    at FunctionDoc.param (node_modules/esdoc/out/src/Doc/FunctionDoc.js:92:61)
    at FunctionDoc._apply (node_modules/esdoc/out/src/Doc/AbstractDoc.js:107:21)
    at FunctionDoc.AbstractDoc (node_modules/esdoc/out/src/Doc/AbstractDoc.js:70:10)
    at new FunctionDoc (node_modules/esdoc/out/src/Doc/FunctionDoc.js:39:77)
    at DocFactory._createDoc (node_modules/esdoc/out/src/Factory/DocFactory.js:635:14)
    at DocFactory._traverseComments (node_modules/esdoc/out/src/Factory/DocFactory.js:565:24)
    at DocFactory.push (node_modules/esdoc/out/src/Factory/DocFactory.js:451:22)
    at Controller.<anonymous> (node_modules/esdoc/out/src/ESDoc.js:443:19)
    at Controller.enter (node_modules/esdoc/out/src/Util/ASTUtil.js:57:20)
```

**Comment by sylvaindethier** [comment]
Weird !! It does not throw that Error on my side.
Using same versions
```javascript
    "esdoc": "^0.4.6",
    "esdoc-es7-plugin": "0.0.3",
```

**Comment by compact** [comment]
For me, that error is being thrown whenever the function is undocumented. If the function is documented with at least one `@param`, then there's no error.

It does not matter whether the function is an export. I'll avoid this by documenting all my (unexported) functions that have rest arguments.

**Comment by duian** [comment]
@compact I add @param to my function, but still error. can you show me your solution?

**Comment by h13i32maru** [comment]
This syntax is not support because the syntax is ES.next. But I want to support the syntax in future version.

**Comment by typhonrt** [comment]
@compact I have a fork of ESDoc that uses the [latest babylon parser w/ all plugins](https://github.com/babel/babylon#plugins) enabled so it works with all ES6 / ES7 / edge code. You can throw anything at it with any ES6+ or even experimental syntax that you would use with Babel itself. object rest spread is supported, etc. https://github.com/typhonjs-node-esdoc/esdoc

@h13i32maru  when you are ready I'd once again like you to consider allowing me to upstream this into ESDoc. There is no "I want to support this" there is only "it's available now, but could be mainlined anytime".

**Comment by h13i32maru** [comment]
@compact Please check [ECMAScript Proposal Feature](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal) via latest ESDoc v0.5
