### ISSUE TITLE
Fails if parameter of function type has no type

### ISSUE THREAD

**Issue by DatenMetzgerX** [esdoc/esdoc#273]
ESdoc fails if a parameter of a function type has no type. 
E.g. 

```
@property {function (node, typeEnvironment: TypeEnvironment): void} analyse ...
```

with the error 

```
node_modules/esdoc/out/src/Publisher/Builder/SingleDocBuilder.js:83
            throw _iteratorError;
            ^

TypeError: Cannot read property 'replace' of undefined
    at node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:924:34
    at Array.map (native)
    at SingleDocBuilder._buildTypeDocLinkHTML (node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:919:41)
    at node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:1301:35
    at IceCap.loop (node_modules/ice-cap/out/src/IceCap.js:319:15)
    at SingleDocBuilder._buildProperties (node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:1285:11)
    at node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:651:41
    at IceCap.loop (node_modules/ice-cap/out/src/IceCap.js:319:15)
    at SingleDocBuilder._buildDetailDocs (node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:606:11)
    at SingleDocBuilder._buildDetailHTML (node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:568:29)
```

It's discussable if this is a valid documentation or not. But it would help if esdoc could point to the location where the documentation syntax is not correct.

**Comment by h13i32maru** [comment]
The your example is invalid syntax. Please try the following code.

```
/**
 * @param {function(node: *, typeEnvironment: TypeEnvironment): void} param - this is example.
 */
export default function foo(param){}
```

ref. https://esdoc.org/tags.html#function

**Comment by bspies-work** [comment]
You will see also the same error if you use ``{*}``, e.g. from a ``@return``. Should ESDoc support this type syntax?
