### ISSUE TITLE
Getting Logger is not a function errors when invoking esdoc cli command for esdoc@0.4.6

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#276]
```
TypeError: Logger is not a function
    at Object.<anonymous> (/usr/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:14:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/esdoc/out/src/Publisher/publish.js:20:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
node_modules/esmake/Makefile.software.in:91: recipe for target 'build-doc-dev' failed
make: *** [build-doc-dev] Error 1
```

**Comment by silkentrance** [comment]
Which might be due to the fact that in color-logger you

```
219 exports.ColorLogger = ColorLogger;
220 const logger = new ColorLogger();
221 logger.debug = true;
222 exports.default = logger;
```

set the default to the instance... why not just reuse winston or some similar such established and well tested logging facility?

**Comment by h13i32maru** [comment]
@silkentrance I fixed the bug last night. Sorry I made the bug by my mistake. Please update esdoc@v0.4.7 :bow:

**Comment by silkentrance** [comment]
@h13i32maru thank you :+1:
