### ISSUE TITLE
ESDoc 0.4.7  issue with dependency

### ISSUE THREAD

**Issue by mrbannon** [esdoc/esdoc#278]
Getting the following when doing require on `node_modules/esdoc/out/src/Publisher/publish.js` (for using the API).

```
let logger = new _colorLogger2.default('IceCap');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/esdoctest/node_modules/esdoc/out/src/Publisher/publish.js:20:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by AnyaYudkovsky** [comment]
Getting same error when trying to run esdoc -h. 
usr/local/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:18
let logger = new _colorLogger2.default('IceCap');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/esdoc/out/src/Publisher/publish.js:20:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by pithu** [comment]
It looks like ESDoc 0.4.7 requires at least node version 4 because of the IceCap dependency. IceCap is using some es6 feature that are not included in node 0.12.

Is that by purpose ?

**Comment by h13i32maru** [comment]
Yes, IceCap requires Node v4 or greater.  Please upgrade your Node version.

**Comment by jadrake75** [comment]
Ok, I filed two bugs with Ice-Cap/Color-Logger.  The problem appears to be that Color-Logger was updated to use Babel/ES6 syntax (cool) but one itty bitty capability was removed.... you can not instantiate Logger with a "tag" (logger name).  It used to be there in older versions and it was removed with the latest.  Even though you may refer to 0.0.3 version, they are not using releases in github.  Since it would appear the "package" in the source package and there is no official version in github (gulp at least) appears to be compiling latest which does not refer to the contructor anymore.   On the esDoc side the fix is simply let logger = Logger; or whatever you imported from color-logger.

**Comment by h13i32maru** [comment]
Please check latest ESDoc with Node.js v6
