### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by damirka** [esdoc/esdoc#301]
Getting this error when trying to generate docs for multiple files.

Here is a log:

```
badge.svg
identifiers.html
index.html
class/components/redis/Connection.js~Connection.html
class/components/errors/DebugError.js~DebugError.html
class/components/errors/EmptyDataError.js~EmptyDataError.html
/usr/lib/node_modules/esdoc/out/src/Publisher/Builder/ClassDocBuilder.js:79
            throw _iteratorError;
            ^
TypeError: Cannot read property 'split' of undefined
    at /usr/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:1287:53
    at IceCap.loop (/usr/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:261:9)
    at ClassDocBuilder._buildProperties (/usr/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:1285:11)
    at /usr/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:651:41
    at IceCap.loop (/usr/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:261:9)
    at ClassDocBuilder._buildDetailDocs (/usr/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:606:11)
    at ClassDocBuilder._buildDetailHTML (/usr/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:568:29)
    at ClassDocBuilder._buildClassDoc (/usr/lib/node_modules/esdoc/out/src/Publisher/Builder/ClassDocBuilder.js:172:44)
    at ClassDocBuilder.exec (/usr/lib/node_modules/esdoc/out/src/Publisher/Builder/ClassDocBuilder.js:64:36)
    at publish (/usr/lib/node_modules/esdoc/out/src/Publisher/publish.js:169:59)
```

And this is my config:

``` JSON
{
  "access": ["public", "protected", "private"],
  "source": "./app/components",
  "destination": "./out/esdoc",
  "undocumentIdentifier": true,
  "unexportIdentifier": true,
  "autoPrivate": false,
  "lint": false
}
```

**Comment by moroine** [comment]
Same issue on my side

**Comment by damirka** [comment]
To @moroine:

I've found a way to fix this but it's completely incorrect and weird. Just added this condition:
```JavaScript
// in /usr/lib/node_modules/esdoc/out/Publisher/Builder/DocBuilder#1288
if (prop.name === undefined) {
    return ice;
}
```

If you need a quick fix to generate docs - this can work. But I don't recommend to do it in any other case.

**Comment by aureooms** [comment]
Here's an example
```js
export class Product {

	constructor ( a , b ) {
		this.a = a ;
		this.b = b ;
	}

	zero ( ) {
		return [ this.a.zero( ) , this.b.zero( ) ] ;
	}

	plus ( [ a , b ] , [ A , B ] ) {
		return [ this.a.plus( a , A ) , this.b.plus( b , B ) ] ;
	}

}
```
Commenting out the `plus` method makes esdoc work again.

**Comment by damirka** [comment]
Seems to me it's somehow related to destructive assignment and it's parsing. Did you try any other ways?

```JavaScript
// like this one
function example({ a: A, b: B}, c = null, [ d = null ]) {
  // check params inside
}
```

**Comment by aureooms** [comment]
No but I think your guess is correct.

**Comment by h13i32maru** [comment]
Thanks for this report.

I will fix this bug in next version.

**Comment by h13i32maru** [comment]
I fixed this bug.
https://github.com/esdoc/esdoc/commit/c8ae3f54837446febb37ac675677d4302552380f

And will release in next version.

**Comment by kumarbhushan** [comment]
Fixed by removing empty param  
 ` *  @apiParam  ` 
^ Remove this
