### ISSUE TITLE
Crash when destructuring an object

### ISSUE THREAD

**Issue by Manuel-Manoury** [esdoc/esdoc#336]
Hi !

During my React development I found out that using ES6 Object destructuring causes ESDoc to crash with the following:

```
TypeError: Cannot read property 'charAt' of undefined
    at Object.<anonymous> (XXX/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:121:39)
    at XXX/node_modules/taffydb/taffy.js:743:17
    at each (XXX/node_modules/taffydb/taffy.js:126:17)
    at Object.<anonymous> (XXX/node_modules/taffydb/taffy.js:740:7)
    at Object.API.(anonymous function) [as update] (XXX/node_modules/taffydb/taffy.js:166:18)
    at DocResolver._resolveAccess (XXX/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:119:20)
    at DocResolver.resolve (XXX/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:51:12)
    at CoverageBuilder.DocBuilder (XXX/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:57:42)
    at new CoverageBuilder (XXX/node_modules/esdoc/out/src/Publisher/Builder/CoverageBuilder.js:35:81)
    at publish (XXX/node_modules/esdoc/out/src/Publisher/publish.js:164:5)
```

The crash is caused by the following syntax:

```
const obj = { 'first' : 'Jane', 'last' : 'Doe' };
const { 'first' : f, 'last' : l } = obj;
// f = 'Jane'; l = 'Doe'
```

There's a simple workaround:

```
const obj = { 'first' : 'Jane', 'last' : 'Doe' };
const f = obj.first;
const l = obj.last;
// f = 'Jane'; l = 'Doe'
```

but this might get messy and unconvenien when the number of attributes "renamed" using this syntax increases.

**Comment by typhonrt** [comment]
The forthcoming v1.0 of ESDoc will support Babylon for the AST generation / parsing. You might give my [current fork of esdoc](https://github.com/esdoc/esdoc/issues/292) a shot as it uses Babylon and should support object destructuring / not crash. If it does though let me know and I'll take a look.

**Comment by Manuel-Manoury** [comment]
Sweet :) thanks for your answer :)

**Comment by typhonrt** [comment]
By chance did my fork (Babylon AST parsing) help / stop ESDoc from crashing? If not I'll look into things as the v1.0 release of ESDoc should / will cover this use case. Welcome to ESDoc BTW! If the fork solves the problem consider closing this issue as the v1.0 mainline release of ESDoc which is switching to Babylon should also solve the issue, but is something to be tracked if not.

**Comment by Manuel-Manoury** [comment]
Hi :) sorry, I maintain a few different projects and I had to switch on another one before having the chance to try your fork :-\ However, I'll try it in the next few hours so as to answer you :)

**Comment by typhonrt** [comment]
No worries.. I'd be glad to try and help out; getting things going with the fork is a bit of a workaround right now, but does help in certain use cases. ESDoc is pretty powerful and the forthcoming v1.0 version should provide significantly better performance with modern syntax.

**Comment by h13i32maru** [comment]
@Manuel-Manoury Please check latest ESDoc v0.5.

I re-open this issue if is problem.
