### ISSUE TITLE
Problem with @returns {Promise<('variant1'|'variant2')>}

### ISSUE THREAD

**Issue by eugen35** [esdoc/esdoc#342]
Hello!
This tag:

```
* @returns {Promise<('grantedToAllSubstances'|'grantedToSomeSubstances'|'notGranted')>}
```

throw **Error Unterminated group at RegExp (native)** by generating doc:

```
C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\ClassDocBuilder.js:79
            throw _iteratorError ;
            ^

SyntaxError: Invalid regular expression: /[~]Promise<('grantedToAllSubstances'\$/: Unterminated group
    at RegExp (native)
    at new RegExp (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\node_modules\core-js\modules\es6.regexp.js:22:11)
    at ClassDocBuilder._findByName (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:140:20)
    at ClassDocBuilder._buildDocLinkHTML (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:1047:22)
    at ClassDocBuilder._buildTypeDocLinkHTML (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:1023:21)
    at ClassDocBuilder._buildSignatureHTML (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:1202:40)
    at C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:512:38
    at IceCap.loop (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\node_modules\ice-cap\out\src\IceCap.js:261:9)
    at ClassDocBuilder._buildSummaryDoc (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:509:11)
    at ClassDocBuilder._buildSummaryHTML (C:\Users\moshchanskiy\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:468:29)
```

**Comment by typhonrt** [comment]
Welcome to ESDoc @eugen35! Please check out the [type syntax](https://esdoc.org/tags.html#type-syntax) section of the documentation. Specifically the `generics` section. You need to specify a `string` as the type. So something like this:

```
* @returns {Promise<('grantedToAllSubstances'|'grantedToSomeSubstances'|'notGranted')>}
```

Should actually be:
```
* @returns {Promise<string>} - Returns a Promise with a string value: 'grantedToAllSubstances', 'grantedToSomeSubstances',
*                              or 'notGranted'.
```

So you need to use the proper type syntax and document any actual values in the text description portion of your documentation. 

If this answers you question please close this issue.

**Comment by eugen35** [comment]
But JSDoc and JetBrains gulps used by me syntax. If you not supported it, may be it will be good to support this?

**Comment by paulondc** [comment]
Hi @eugen35,

The documentation (https://esdoc.org/tags.html) under the Generic sections says to separate them using comma, it seems the official way:

***Generics***
```es6

/**
 * @param {Array<string>} param - this is Array param.
 */
function myFunc(param){...}

/**
 * @param {Map<number, string>} param - this is Map param.
 */
function myFunc(param){...}

/**
 * @return {Promise<string[], MyError>} this is Promise return value.
 */
function myFunc(){...}
```

However that operator is a bit confused because for parameter types it requires "|". I would expect the operator "or" to be represented in the same way everywhere, either "," or  "|" but not both.

Cheers

**Comment by eugen35** [comment]
Hello. I have mentioned this case: [How to document a string type in jsdoc with limited possible values](http://stackoverflow.com/questions/19093935/how-to-document-a-string-type-in-jsdoc-with-limited-possible-values). There is written:

> As of late 2014 in jsdoc3 you have the possibility to write:

``````
/**
 * @param {('rect'|'circle'|'ellipse')} shapeType - The allowed type of the shape
 */
Shape.prototype.getType = function (shapeType) {
  return this.type;
};
``````
> Of course this will not be as reusable as a dedicated enum but in many cases a dummy enum is an overkill if it is only used by one function.

> See also: https://github.com/jsdoc3/jsdoc/issues/629#issue-31314808

And i wwill go further:
``````
/**
* @returns {Promise<('square'|'circle'|'another figure')>}
*/
class whatFigure ( params ) {
  switch (...) {
    case (...) :  return 'square'
    case (...) :  return 'circle'
    default: return 'another figure'
  }
}

**Comment by h13i32maru** [comment]
@eugen35 I fixed this issue. And I will release in next version.

```js
/**
 * @param {Promise<string|number>} p1
 * @param {Array<string|null>} p2
 */
export function foo(p1, p2){}
```
