### ISSUE TITLE
Array destructuring with gaps fails

### ISSUE THREAD

**Issue by tex0l** [esdoc/esdoc#350]
Hi,
ESDoc seems to be unable to parse this line of code:
```javascript
const [ , , size ] = process.argv
```

It gives the following error:
```
TypeError: Cannot read property 'name' of null
    at VariableDoc._name (/usr/local/lib/node_modules/esdoc/out/src/Doc/VariableDoc.js:70:71)
    at VariableDoc._apply (/usr/local/lib/node_modules/esdoc/out/src/Doc/AbstractDoc.js:86:21)
    at VariableDoc.AbstractDoc (/usr/local/lib/node_modules/esdoc/out/src/Doc/AbstractDoc.js:70:10)
    at new VariableDoc (/usr/local/lib/node_modules/esdoc/out/src/Doc/VariableDoc.js:39:77)
    at DocFactory._createDoc (/usr/local/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:635:14)
    at DocFactory._traverseComments (/usr/local/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:565:24)
    at DocFactory.push (/usr/local/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:451:22)
    at Controller.<anonymous> (/usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:443:19)
    at Controller.enter (/usr/local/lib/node_modules/esdoc/out/src/Util/ASTUtil.js:57:20)
    at Controller.__execute (/usr/local/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/esdoc/node_modules/estraverse/estraverse.js:495:28)
```

Is this normal ?

**Comment by h13i32maru** [comment]
Thanks reporting.

I fixed it. And release in next version
https://github.com/esdoc/esdoc/commit/075c54bef5038588be56e0da4d95906732750cd0
