### ISSUE TITLE
Support object rest spread with default parameter

### ISSUE THREAD

**Issue by shotamatsuda** [esdoc/esdoc#377]
There's a similar issue regarding babel (https://github.com/jhen0409/babel-preset-es2015-node6/issues/2), which can be workaround using `transform-es2015-destructuring` and `transform-es2015-parameters`. I know it's not an esdoc's issue but an parser's issue, but if you already have encountered this problem and know a workaround for this, please let me know.

This throws a parser error:

```
class T extends U {
  constructor({ some, ...rest } = {}) {
    super({ ...rest })
    this.some = some
  }
}
```

As follows:

```
error: could not process the following code.
./src/Test.js
0| undefined
1| export class T extends U {
2|   constructor({ some, ...rest } = {}) {

./node_modules/esdoc/out/src/ESDoc.js:303
        throw e;
        ^

TypeError: Cannot read property 'name' of undefined
    at Function.guessParams (./node_modules/esdoc/out/src/Parser/ParamParser.js:244:31)
    at MethodDoc._$param (./node_modules/esdoc/out/src/Doc/MethodDoc.js:78:48)
    at MethodDoc._apply (./node_modules/esdoc/out/src/Doc/AbstractDoc.js:97:10)
    at MethodDoc._apply (./node_modules/esdoc/out/src/Doc/MethodDoc.js:30:11)
    at MethodDoc.AbstractDoc (./node_modules/esdoc/out/src/Doc/AbstractDoc.js:56:10)
    at MethodDoc (./node_modules/esdoc/out/src/Doc/MethodDoc.js:24:1)
    at DocFactory._createDoc (./node_modules/esdoc/out/src/Factory/DocFactory.js:455:12)
    at DocFactory._traverseComments (./node_modules/esdoc/out/src/Factory/DocFactory.js:396:20)
    at DocFactory.push (./node_modules/esdoc/out/src/Factory/DocFactory.js:349:20)
    at _ASTUtil2.default.traverse (./node_modules/esdoc/out/src/ESDoc.js:300:17)
```

**Comment by mikeyGlitz** [comment]
I'm having the same problem; even with 

`
"experimentalProposal": {
   "objectRestSpread": true
}
`

in my config file.
