### ISSUE TITLE
error at the end of generating document

### ISSUE THREAD

**Issue by fingerpich** [esdoc/esdoc#384]
# error at the end of generating document
i have trouble with another error which has fixed by upgrading node js and then i have faced with this error

# Input data for reproducing
{
  "source": "./src",
  "destination": "./doc"
}
```

#### Codes
./src/ControllerElement.js
```
import { h } from 'preact';

/**
 * @param {number} width sinus width
 * @param {number} step steps in x
 * @param {number} start start sinus at
 * @param {function} onChange event callback
 * @return {object} presentation element
 */
const ControllerElement = ({onChange, width=5, step=1, start=0}) => (
);

export default ControllerElement;
```

# Output data
#### Log
```
Coverage: 28.57% (2/7)

TypeError: Cannot read property 'length' of undefined
    at LintDocBuilder._showResult (C:\Users\mojtaba\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\LintDocBuilder.js:150:64)
    at LintDocBuilder.exec (C:\Users\mojtaba\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\Builder\LintDocBuilder.js:52:10)
    at publish (C:\Users\mojtaba\AppData\Roaming\npm\node_modules\esdoc\out\src\Publisher\publish.js:177:48)
    at Function.generate (C:\Users\mojtaba\AppData\Roaming\npm\node_modules\esdoc\out\src\ESDoc.js:137:7)
    at ESDocCLI.exec (C:\Users\mojtaba\AppData\Roaming\npm\node_modules\esdoc\out\src\ESDocCLI.js:75:23)
    at Object.<anonymous> (C:\Users\mojtaba\AppData\Roaming\npm\node_modules\esdoc\out\src\ESDocCLI.js:186:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```

# Your environment
- OS type and version: windows 10
- Node.js version: 6.7
- ESDoc version: 0.5.2

**Comment by thurt** [comment]
same issue:
```
TypeError: Cannot read property 'length' of undefined
    at LintDocBuilder._showResult (/Users/thurt/projects/autonation-native/node_modules/esdoc/out/src/Publisher/Builder/LintDocBuilder.js:150:64)
    at LintDocBuilder.exec (/Users/thurt/projects/autonation-native/node_modules/esdoc/out/src/Publisher/Builder/LintDocBuilder.js:52:10)
    at publish (/Users/thurt/projects/autonation-native/node_modules/esdoc/out/src/Publisher/publish.js:177:48)
    at Function.generate (/Users/thurt/projects/autonation-native/node_modules/esdoc/out/src/ESDoc.js:137:7)
    at ESDocCLI.exec (/Users/thurt/projects/autonation-native/node_modules/esdoc/out/src/ESDocCLI.js:75:23)
    at Object.<anonymous> (/Users/thurt/projects/autonation-native/node_modules/esdoc/out/src/ESDocCLI.js:186:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by thurt** [comment]
exact same stack trace issue here

**Comment by thurt** [comment]
@fingerpich this appears to be an error generated during the lint phase, which does not affect the actual document generation as far as I can tell.

try disabling lint checking. that worked for me:
https://esdoc.org/manual/usage/feature.html#documentation-lint

 "Note: For now, ESDoc lints only method/function signature."

**Comment by thurt** [comment]
@h13i32maru i see the lint error when the number of @ param tags is greater than the actual number of params, like shown in @fingerpich example above.

However, if they are the same number, then it will NOT generate the error. 

for example, this works fine when lint: true
```
/**
* @param {object} props
* @param {object} extraParam
*/
const ControllerElement = ({onChange, width=5, step=1, start=0}, extraParam) => (
);
```

**Comment by fingerpich** [comment]
Thank you

**Comment by folkvir** [comment]
@thurt Thank you I had the same error and I corrected it by removing one extra @param.
