### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by iffy** [esdoc/esdoc#388]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [X] https://esdoc.org/manual/usage/feature.html
- [X] https://esdoc.org/manual/configuration/config.html
- [X] https://esdoc.org/manual/usage/tags.html  I have no tags at all... and my source code builds fine on try.esdoc.org
- [X] https://esdoc.org/manual/advanced/api.html
- [X] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue

Running `esdoc` I get this stacktrace:

```
TypeError: Cannot read property '1' of null
Please report this to https://github.com/chjj/marked.
    at Object.sanitizer (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/util.js:89:46)
    at InlineLexer.output (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:612:26)
    at Parser.tok (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:1075:50)
    at Parser.parse (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:935:17)
    at Function.Parser.parse (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:922:17)
    at marked (/Users/matt/m/lhtml/node_modules/marked/lib/marked.js:1219:19)
    at markdown (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/util.js:80:41)
    at IndexDocBuilder._buildIndexDoc (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/IndexDocBuilder.js:73:44)
    at IndexDocBuilder.exec (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/Builder/IndexDocBuilder.js:49:30)
    at publish (/Users/matt/m/lhtml/node_modules/esdoc/out/src/Publisher/publish.js:146:58)
```

I've reported it here like it told me to: https://github.com/chjj/marked/issues/851

# Input data for reproducing
#### Configuration
```json
{
    "source": "./guest",
    "destination": "./doc"
}
```

#### Codes
https://github.com/iffy/lhtml/tree/docs/guest (You can checkout the `docs` branch of that repo to reproduce, probably.

# Your environment
```
$ esdoc --version
0.5.2
$ node --version
v7.4.0
$ uname -a
Darwin Matts-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64 x86_64
```

**Comment by marvin89** [comment]
Hi @iffy 

I just encountered the same issue and managed to solve mine by inspecting the README.md file. In my case there were "comment tags" at the bottom:

```markdown
<!--
Some old stuff
-->
```

After removing all of that generation was successful. It looks like you also have those in your README.md

**Comment by iffy** [comment]
Yep, seems like it was that.  That it looks at `README.md` is a completely unexpected behavior (and that it doesn't mention the file in the error, too)

(I changed `.esdoc.json`'s `index` to a bogus file and that fixed it for me).
