### ISSUE TITLE
Unable to run esdoc version 0.5.x, have to rollback to 0.4.x

### ISSUE THREAD

**Issue by andy-law** [esdoc/esdoc#390]
# Short summary of issue
I'm unable to use version 0.5.x of esdoc, as I get an exception everytime I try to generate my docs. I have to roll back to using version 0.4.x for the moment as this still works. The exception that I get is as follows:
```
parse: [projectDir]/src/index.js
[projectDir]/node_modules/esdoc/out/src/Factory/DocFactory.js:136
    for (const exportNode of this._ast.program.body) {
                                              ^

TypeError: Cannot read property 'body' of undefined
    at DocFactory._inspectExportDefaultDeclaration ([projectDir]/node_modules/esdoc/out/src/Factory/DocFactory.js:136:47)
    at new DocFactory ([projectDir]/node_modules/esdoc/out/src/Factory/DocFactory.js:91:10)
    at Function._traverse ([projectDir]/node_modules/esdoc/out/src/ESDoc.js:296:21)
    at _walk.filePath ([projectDir]/node_modules/esdoc/out/src/ESDoc.js:119:25)
    at Function._walk ([projectDir]/node_modules/esdoc/out/src/ESDoc.js:266:9)
    at Function.generate ([projectDir]/node_modules/esdoc/out/src/ESDoc.js:103:10)
    at ESDocCLI.exec ([projectDir]/node_modules/esdoc/out/src/ESDocCLI.js:75:23)
    at Object.<anonymous> ([projectDir]/node_modules/esdoc/out/src/ESDocCLI.js:186:7)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
```
My esdoc.json config file (which seems pretty simple and standard) looks like this:
```
{
  "source": "./src",
  "destination": "./docs",
  "plugins": [
    {"name": "esdoc-es7-plugin"}
  ],
  "lint": true,
  "includes": ["^[^\\.]*\\.js$"],
  "excludes": [".*node_modules.*", "\\.spec\\.js", "^build/.*"]
}
```

# Runtime environment
- OS type and version: Mac OS 10.12
- Node.js version: v7.1.0
- ESDoc version: v0.5.x

**Comment by erkmos** [comment]
I had the same issue, the problem is with the esdoc-es7-plugin. Luckily it seems to mostly be made redundant by newer version of esdoc. You can get the same(?) functionality by adding

```
"experimentalProposal": {
    "classProperties": true,
    "objectRestSpread": true,
    "decorators": true,
    "doExpressions": true,
    "functionBind": true,
    "asyncGenerators": true,
    "exportExtensions": true,
    "dynamicImport": true
  }
```

To to your ```.esdoc``` file and removing the ```esdoc-es7-plugin``` from your plugins list

**Comment by andy-law** [comment]
Perfect, thanks for your help with this @erkmos, that's working perfectly now.
