### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by 3axap4eHko** [esdoc/esdoc#391]
just fall down on string
`@param {string|number|{key, value}} [defaultKey]`
it happens on line [DocBuilder.js:753](https://github.com/esdoc/esdoc/blob/master/src/Publisher/Builder/DocBuilder.js#L753)
``` javascript
const tmp = v.split(':').map((v)=> v.trim());
const paramName = tmp[0];
let typeName = tmp[1].replace(/\\Z/g, ',').replace(/\\Y/g, ':');
```
there are no check for `tmp.length`

**Comment by polakj** [comment]
Up

**Comment by QuentinRoy** [comment]
I have the same error. No idea where it comes from in my code. I used the syntax as code documentation but never run esdoc before recently. The error message does not give me any opportunity to fix whatever is wrong..

**Comment by Kepro** [comment]
same here...

````
TypeError: Cannot read property 'replace' of undefined
    at inner.split.map.v (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:779:30)
    at Array.map (native)
    at ClassDocBuilder._buildTypeDocLinkHTML (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:776:43)
    at ClassDocBuilder._buildSignatureHTML (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:923:36)
    at ice.loop (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:410:34)
    at IceCap.loop (/usr/local/lib/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:261:9)
    at ClassDocBuilder._buildSummaryDoc (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:406:9)
    at ClassDocBuilder._buildSummaryHTML (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:383:27)
    at ClassDocBuilder._buildClassDoc (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/ClassDocBuilder.js:119:36)
    at ClassDocBuilder.exec (/usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/ClassDocBuilder.js:35:32)
````

**Comment by rayk** [comment]
Same problem here...

```
TypeError: Cannot read property 'replace' of undefined
    at inner.split.map.v (/Users/rayk/Projects/criticide/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:700:30)
    at Array.map (native)
    at IdentifiersDocBuilder._buildTypeDocLinkHTML (/Users/rayk/Projects/criticide/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:697:43)
    at IdentifiersDocBuilder._buildSignatureHTML (/Users/rayk/Projects/criticide/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:844:36)
    at ice.loop (/Users/rayk/Projects/criticide/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:333:34)
    at IceCap.loop (/Users/rayk/Projects/criticide/node_modules/ice-cap/out/src/IceCap.js:261:9)
    at IdentifiersDocBuilder._buildSummaryDoc (/Users/rayk/Projects/criticide/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:329:9)
    at ice.loop (/Users/rayk/Projects/criticide/node_modules/esdoc-publish-html-plugin/out/src/Builder/IdentifiersDocBuilder.js:75:28)
    at IceCap.loop (/Users/rayk/Projects/criticide/node_modules/ice-cap/out/src/IceCap.js:261:9)
    at IdentifiersDocBuilder._buildIdentifierDoc (/Users/rayk/Projects/criticide/node_modules/esdoc-publish-html-plugin/out/src/Builder/IdentifiersDocBuilder.js:60:9)```

This was run against a simple out of the `react-create` project.

**Comment by raziza** [comment]
I had the same problem. and narrowed my code so i found my file that cause problem.
after debuging esdoc found out that I had `@param {{x,y}} point ...` and it expected types after each property.
correct syntax is `@param {{x:Number,y:Number}} point ...`.. Now it is working.
Yes bug in `esdoc` but you can never cover all cases.

Hope it will help someone

**Comment by iursevla** [comment]
Had the same problem as @raziza.

**Comment by sidoruk-sv** [comment]
Got the same error, but my code base is too big for inspecting for the problem, described by @raziza.

I think it's better to add a check for `tmp.length` AND provide meaningful error with stack trace to `../file:Line:column`, where the problem occurs.

**Comment by bwyss** [comment]
I am getting this error in version 0.40.1 when:

map.fitBounds (to some enveloped geometry) followed by map.addLayer. I found that if I first create the layer, then fitBounds everything is happy

**Comment by Kepro** [comment]
@3axap4eHko closed after 3 years without any word?

**Comment by 3axap4eHko** [comment]
@Kepro just cleaning up hanging issues
