### ISSUE TITLE
bug when trying to run esdoc through npm script

### ISSUE THREAD

**Issue by natehardy** [esdoc/esdoc#396]
# Short summary of your issue
when running esdoc, I get an error:
\ESDoc.js:121
      results.push(...temp.results);
                   ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (..\node_modules\esdoc\out\src\ESDocCLI.js:20:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

# Input data for reproducing
I have a npm script in package.json:
"doc": "esdoc -c esdoc.json"

esdoc.json = {
  "source": "./src",
  "destination": "./doc",
  "lint": true,
  "experimentalProposal": {
    "classProperties": true,
    "objectRestSpread": true,
    "decorators": true,
    "doExpressions": true,
    "functionBind": true,
    "asyncGenerators": true,
    "exportExtensions": true,
    "dynamicImport": true
  }
}

# Your environment
- Windows 10
- Node.js version: 4.2.0
- ESDoc version: 0.5.2

**Comment by truedat101** [comment]
Broken for me on Linux, node.js version 4.3.2.

**Comment by noahbenham** [comment]
Probably related to #369. Does updating to node 6+ resolve issues?
