### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by zemzheng** [esdoc/esdoc#430]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/usage/feature.html
- [x] https://esdoc.org/manual/configuration/config.html
- [x] https://esdoc.org/manual/usage/tags.html
- [x] https://esdoc.org/manual/advanced/api.html
- [x] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue
Run esdoc and meet the Error
```
TypeError: Cannot read property 'name' of null
```

# Input data for reproducing
#### Configuration
```json
{
  "source": "./src",
  "destination": "./doc/src",
  "includes": ["\\.(js|jsx)$"],
  "excludes": ["\\_\\_test\\_\\_", "config\\.js"],
  "experimentalProposal": {
    "classProperties": true,
    "objectRestSpread": true,
    "decorators": true,
    "doExpressions": true,
    "functionBind": true,
    "asyncGenerators": true,
    "exportExtensions": true,
    "dynamicImport": true
  }
}
```

#### Codes
```js
const myAudio = new Audio;
```

# Output data
#### Log
```
TypeError: Cannot read property 'name' of null
....
```

#### Screen shot of documentation
![image](https://user-images.githubusercontent.com/650956/26915866-5a30cdae-4c5a-11e7-836e-ef4038efcbc3.png)

# Your environment
- OS type and version: Win7
- Node.js version: v7.9.0
- ESDoc version: v0.5.2

**Comment by wbhob** [comment]
You have to define a plugin

**Comment by zemzheng** [comment]
@wbhob why i should define a plugin if i want to use Audio which is supported in browser?

**Comment by h13i32maru** [comment]
I fixed this with f3d3f0f

**Comment by loveneetsingh4** [comment]
annot read property 'name' of null
    at eval (eval at compile (/home/ubuntu/workspace/yelpcamp/little/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:34:35)
    at returnedFn (/home/ubuntu/workspace/yelpcamp/little/node_modules/ejs/lib/ejs.js:653:17)
    at tryHandleCache (/home/ubuntu/workspace/yelpcamp/little/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/home/ubuntu/workspace/yelpcamp/little/node_modules/ejs/lib/ejs.js:482:10)
    at View.render (/home/ubuntu/workspace/yelpcamp/little/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/ubuntu/workspace/yelpcamp/little/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/home/ubuntu/workspace/yelpcamp/little/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/ubuntu/workspace/yelpcamp/little/node_modules/express/lib/response.js:1008:7)
    at /home/ubuntu/workspace/yelpcamp/little/routes/campgrounds.js:11:14
    at /home/ubuntu/workspace/yelpcamp/little/node_modules/mongoose/lib/model.js:4495:16
    at Query._completeOne (/home/ubuntu/workspace/yelpcamp/little/node_modules/mongoose/lib/query.js:1834:12)
    at Immediate.Query.base.findOne.call (/home/ubuntu/workspace/yelpcamp/little/node_modules/mongoose/lib/query.js:1894:10)
    at Immediate.<anonymous> (/home/ubuntu/workspace/yelpcamp/little/node_modules/mquery/lib/utils.js:116:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by loveneetsingh4** [comment]
how i will  fix this error?
