### ISSUE TITLE
esdoc breaks if no README.md present

### ISSUE THREAD

**Issue by 22a** [esdoc/esdoc#432]
The latest release, `v1.0.0-alpha.3`, breaks if `README.md` is not present. Surely esdoc should not be dependent on a project having a readme and naming it `README.md`.

# Input data for reproducing

#### Installation
```bash
yarn add esdoc@v1.0.0-alpha.3 esdoc-standard-plugin --dev
```
#### Configuration
```json
{
  "source": "./lib",
  "destination": "./esdoc",
  "plugins": [{
    "name": "esdoc-standard-plugin"
  }]
}
```
#### Usage
```bash
./node_modules/.bin/esdoc
```

# Exception output
#### Log
```
// write into here
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './README.md'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function._generateForIndex (/Users/peter/<<PATH>>/<<REPO_NAME>>/node_modules/esdoc/out/src/ESDoc.js:325:44)
    at Function.generate (/Users/peter/<<PATH>>/<<REPO_NAME>>/node_modules/esdoc/out/src/ESDoc.js:130:25)
    at ESDocCLI.exec (/Users/peter/<<PATH>>/<<REPO_NAME>>/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/Users/peter/<<PATH>>/<<REPO_NAME>>/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

# Temporary Fix
```bash
touch README.md
```

# Your environment
- OS type and version: macOS v 10.12.5
- Node.js version: 6.10.0
- ESDoc version: v1.0.0-alpha.3

**Comment by scaljeri** [comment]
+1 same issue here. Thnx for the fix!

    "dependencies": {
        "esdoc": "^1.0.1",
        "esdoc-standard-plugin": "^1.0.0"
    }

**Comment by Benno007** [comment]
Same issue here. It also has the issue of the file is `readme.md` instead of README.md.

**Comment by felzix** [comment]
Is this something that's every going to get fixed?

**Comment by TurboTim** [comment]
Same issue, any update?

**Comment by TheDavaakhuu** [comment]
Bug is still actual

**Comment by 22a** [comment]
PR opened

**Comment by MattMcFarland** [comment]
Feel free to send a PR to esdoc2 https://github.com/esdoc2/esdoc2.git
