### ISSUE TITLE
Error: unknown decorator expression type: MemberExpression

### ISSUE THREAD

**Issue by khaiphan** [esdoc/esdoc#439]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/usage/feature.html
- [x] https://esdoc.org/manual/configuration/config.html
- [x] https://esdoc.org/manual/usage/tags.html
- [x] https://esdoc.org/manual/advanced/api.html
- [x] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue
`Error: unknown decorator expression type: MemberExpression`
# Input data for reproducing
#### Configuration
```json
{
  "source": "./src",
  "destination": "./doc",
  "excludes": [
    ["\\.config\\.(js|es6)$"]
  ],
  "experimentalProposal": {
    "classProperties": true,
    "objectRestSpread": true,
    "decorators": true,
    "doExpressions": true,
    "functionBind": true,
    "asyncGenerators": true,
    "exportExtensions": true,
    "dynamicImport": true
  },
  "plugins": [{
    "name": "esdoc-standard-plugin"
  }]
}
```

#### Codes
```js
import { observable, action } from 'mobx'
import TransactionColumns from './transactionColumns'
import TransactionColumnsOptions from './transactionColumnsOptions'

export default class {
  @observable.ref transactionColumnsState = [
    'processing_timestamp',
    'core_transaction_id',
    'customer_name_given',
    'processing_result'
  ]
  @observable.ref transactionColumns = TransactionColumns(this.transactionColumnsState)
  @observable.ref transactionColumnsOptions = TransactionColumnsOptions(this.transactionColumns)
  @observable.ref filtered = [{
    id: 'processing_result',
    value: ''
  }]
  @action.bound
  setFiltered (data) {
    this.filtered = data
  }
  @action.bound
  setTransactionsColumnsState (data) {
    this.transactionColumnsState = data
    this.transactionColumns = TransactionColumns(this.transactionColumnsState)
    this.transactionColumnsOptions = TransactionColumnsOptions(this.transactionColumns)
  }
}
```

# Output data
#### Log
```
error: could not process the following code.
/Users/khaiphan/Documents/Projects/nfq/alice/src/containers/Transactions/model/transaction.js
0| undefined
1| import { observable, action } from 'mobx'
2| import TransactionColumns from './transactionColumns'
3| import TransactionColumnsOptions from './transactionColumnsOptions'
4|
5| export default class {
6|   @observable.ref transactionColumnsState = [

/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/ESDoc.js:303
        throw e;
        ^

Error: unknown decorator expression type: MemberExpression
    at ClassPropertyDoc._$decorator (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Doc/AbstractDoc.js:578:17)
    at ClassPropertyDoc._apply (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Doc/AbstractDoc.js:106:10)
    at ClassPropertyDoc._apply (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Doc/ClassPropertyDoc.js:30:11)
    at ClassPropertyDoc.AbstractDoc (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Doc/AbstractDoc.js:56:10)
    at ClassPropertyDoc (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Doc/ClassPropertyDoc.js:24:1)
    at DocFactory._createDoc (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Factory/DocFactory.js:455:12)
    at DocFactory._traverseComments (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Factory/DocFactory.js:396:20)
    at DocFactory.push (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Factory/DocFactory.js:349:20)
    at _ASTUtil2.default.traverse (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/ESDoc.js:300:17)
    at enter (/Users/khaiphan/Documents/Projects/nfq/alice/node_modules/esdoc/out/src/Util/ASTUtil.js:39:9)
```

#### Screen shot of documentation
// attach a image into here

# Exception output (if possible)
#### Log
```
error: could not process the following code.
```

#### Screen shot of documentation
![Image](http://i.imgur.com/eNlEFqg.png)

# Your environment
- OS type and version: OSX Sierra v10.12
- Node.js version: 8
- ESDoc version: 0.5.2

**Comment by h13i32maru** [comment]
I fixed this issue with ESDoc v1.0.3 and esdoc-ecmascript-proposal-plugin.
Please check it.
