### ISSUE TITLE
Tags conflict with ES2016 decorators.

### ISSUE THREAD

**Issue by marcdavi-es** [esdoc/esdoc#463]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [ ] https://esdoc.org/manual/usage/feature.html
- [ ] https://esdoc.org/manual/configuration/config.html
- [ ] https://esdoc.org/manual/usage/tags.html
- [ ] https://esdoc.org/manual/advanced/api.html
- [ ] https://esdoc.org/manual/faq/faq.html
☝️  These links appear to be dead?

# Short summary of your issue
Tag parsing conflicts with the usage of ES2016 decorators. 

Specifically - I use ES2016 decorators to wrap React components with the [redux form higher order component](https://redux-form.com/7.0.4/docs/api/reduxform.md/)

```js

@reduxForm({form: FORM_NAME})
export class SomeForm extends Component {

```

Esdoc appears to interpret `@reduxForm` as an Esdoc tag and throws

```
SyntaxError: Invalid regular expression: /[~]reduxForm
  form: FORM_NAME
})$/: Unmatched ')'
```

# Input data for reproducing
#### Configuration
```json
{
  "source": "./src",
  "destination": "./esdoc",
  "excludes": [
    "config/*"
  ],
  "plugins": [
    {
      "name": "esdoc-standard-plugin",
      "option": {
        "lint": {"enable": true},
        "coverage": {"enable": true},
        "manual": {
          ...
        }
      }
    },
    {
      "name": "esdoc-ecmascript-proposal-plugin",
      "option": {"all": true}
    },
    {
      "name": "esdoc-jsx-plugin",
      "option": {"enable": true}
    }
  ]
}
```

#### Codes
```js

@reduxForm({form: FORM_NAME})
export class SomeForm extends Component {

```

# Output data
#### Log
```
SyntaxError: Invalid regular expression: /[~]reduxForm
  form: FORM_NAME
})$/: Unmatched ')'
```

# Your environment
- OS type and version: Mac OSX Sierra
- Node.js version: v7.10.0
- ESDoc version: v1.0.3

**Comment by ChrisRast** [comment]
Copied from another issue I reported before seeing this one:

---

# Short summary of your issue
ESdoc 1.0.3 crashes during output. It's a regression from 1.0.2 which is working well.

# Input data for reproducing
#### Configuration
```json
{
  "source": "./fuel/app",
  "destination": "./docs/js/esdoc",
  "plugins": [{
      "name": "esdoc-standard-plugin",
      "options": {
        "manual": {
          "index": "./docs/app.md",
          "asset": "./docs/assets",
          "files": [
            "./CHANGELOG.md",
            "./BRANCHLOG.md"
          ]
        }
      }
    },
    {
      "name": "esdoc-ecmascript-proposal-plugin",
      "option": {
        "all": true
      }
    },
    {
      "name": "esdoc-jsx-plugin"
    }
  ]
}

```

#### Codes
```js
import PropTypes from 'prop-types';
import React from 'react';
import {connect} from 'react-redux';
import {stateProxy} from 'app/stores';
import Layout from './layout';

/**
 * Decorator
 * Redux pattern http://rackt.org/redux/docs/basics/UsageWithReact.html
 * Inject dispatch function as property in the component
 * All key of the returned object as injected as properties in the component
 * @method connect
 * @param  {Object}  state  Current state
 * @return {Object}  State properties to inject as properties
 */
@connect((state, props) => {
	const currentState = stateProxy(state.actionbar, 'default');

	return {
		content: currentState.get('content'),
	};
})

/**
 * Actionbar Layout Class
 *
 * @class Actionbar
 * @extends {Layout}
 */
export default class Actionbar extends Layout {
     // ...
     // the file continues ...
```

# Output data
#### Log
```
SyntaxError: Invalid regular expression: /[~]connect
  const currentState = stateProxy(state.actionbar, 'default');
  return {
    content: currentState.get('content')
  };
})$/: Unmatched ')'
    at RegExp (<anonymous>)
    at ClassDocBuilder._findByName (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:116:20)
    at ClassDocBuilder._buildDocLinkHTML (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:768:22)
    at ClassDocBuilder._buildDecoratorHTML (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:1012:25)
    at ClassDocBuilder._buildClassDoc (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/ClassDocBuilder.js:87:32)
    at ClassDocBuilder.exec (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/ClassDocBuilder.js:31:32)
    at Plugin._exec (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Plugin.js:93:63)
    at Plugin.onPublish (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Plugin.js:71:10)
    at Plugin._execHandler (/data/web/esl/solar/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onPublish (/data/web/esl/solar/node_modules/esdoc/out/src/Plugin/Plugin.js:154:10)
```

# Your environment
- OS type and version: MacOS 10.12
- Node.js version: 8.6
- ESDoc version: 1.0.3
**Note:** This is not happening with 1.0.2

Do you need more info?
