### ISSUE TITLE
v1.0.3: SyntaxError: Invalid regular expression: /[~]connect

### ISSUE THREAD

**Issue by ChrisRast** [esdoc/esdoc#473]
# Short summary of your issue
ESdoc 1.0.3 crashes during output. It's a regression from 1.0.2 which is working well.

# Input data for reproducing
#### Configuration
```json
{
  "source": "./fuel/app",
  "destination": "./docs/js/esdoc",
  "plugins": [{
      "name": "esdoc-standard-plugin",
      "options": {
        "manual": {
          "index": "./docs/app.md",
          "asset": "./docs/assets",
          "files": [
            "./CHANGELOG.md",
            "./BRANCHLOG.md"
          ]
        }
      }
    },
    {
      "name": "esdoc-ecmascript-proposal-plugin",
      "option": {
        "all": true
      }
    },
    {
      "name": "esdoc-jsx-plugin"
    }
  ]
}

```

#### Codes
```js
import PropTypes from 'prop-types';
import React from 'react';
import {connect} from 'react-redux';
import {stateProxy} from 'app/stores';
import Layout from './layout';

/**
 * Decorator
 * Redux pattern http://rackt.org/redux/docs/basics/UsageWithReact.html
 * Inject dispatch function as property in the component
 * All key of the returned object as injected as properties in the component
 * @method connect
 * @param  {Object}  state  Current state
 * @return {Object}  State properties to inject as properties
 */
@connect((state, props) => {
	const currentState = stateProxy(state.actionbar, 'default');

	return {
		content: currentState.get('content'),
	};
})

/**
 * Actionbar Layout Class
 *
 * @class Actionbar
 * @extends {Layout}
 */
export default class Actionbar extends Layout {
     // ...
     // the file continues ...
```

# Output data
#### Log
```
SyntaxError: Invalid regular expression: /[~]connect
  const currentState = stateProxy(state.actionbar, 'default');
  return {
    content: currentState.get('content')
  };
})$/: Unmatched ')'
    at RegExp (<anonymous>)
    at ClassDocBuilder._findByName (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:116:20)
    at ClassDocBuilder._buildDocLinkHTML (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:768:22)
    at ClassDocBuilder._buildDecoratorHTML (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:1012:25)
    at ClassDocBuilder._buildClassDoc (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/ClassDocBuilder.js:87:32)
    at ClassDocBuilder.exec (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Builder/ClassDocBuilder.js:31:32)
    at Plugin._exec (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Plugin.js:93:63)
    at Plugin.onPublish (/data/web/esl/solar/node_modules/esdoc-publish-html-plugin/out/src/Plugin.js:71:10)
    at Plugin._execHandler (/data/web/esl/solar/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onPublish (/data/web/esl/solar/node_modules/esdoc/out/src/Plugin/Plugin.js:154:10)
```

# Your environment
- OS type and version: MacOS 10.12
- Node.js version: 8.6
- ESDoc version: 1.0.3
**Note:** This is not happening with 1.0.2

Do you need more info?

**Comment by ChrisRast** [comment]
Same issue as #463 . I close this one.
