### ISSUE TITLE
SyntaxError: Unexpected token ? in JSON at position 0

### ISSUE THREAD

**Issue by waltergms** [esdoc/esdoc#477]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [ ] https://esdoc.org/manual/usage/feature.html
- [ ] https://esdoc.org/manual/configuration/config.html
- [ ] https://esdoc.org/manual/usage/tags.html
- [ ] https://esdoc.org/manual/advanced/api.html
- [ ] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue
Cant run esdocs -c, cant parse json

# Input data for reproducing
#### Configuration
```json
{
	"source": "./src",
	"destination": "./docs",
	"plugins": [
		{ "name": "esdoc-standard-plugin" }
	]
}
```

#### Codes
```js
esdoc -c esdoc.json
```

# Output data
#### Log
```
undefined:1
?{
^

SyntaxError: Unexpected token ? in JSON at position 0
    at JSON.parse (<anonymous>)
    at ESDocCLI._createConfigFromJSONFile (C:\Users\Administrador\AppData\Roaming\npm\node_modules\esdoc\out\src\ESDocCLI.js:153:27)
    at ESDocCLI.exec (C:\Users\Administrador\AppData\Roaming\npm\node_modules\esdoc\out\src\ESDocCLI.js:65:21)
    at Object.<anonymous> (C:\Users\Administrador\AppData\Roaming\npm\node_modules\esdoc\out\src\ESDocCLI.js:182:7)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)

```

#### Screen shot of documentation
// attach a image into here

# Exception output (if possible)
#### Log
```
// write into here
```

#### Screen shot of documentation
// attach a image into here

# Your environment
- OS type and version: Windows Server 2012 Rc2
- Node.js version: 8.5.0
- ESDoc version: 1.0.3

**Comment by waltergms** [comment]
Json identation must be 2 spaces not TAB.
Can be closed.

**Comment by pixelass** [comment]
@waltergms you can close issues yourself. 

Also the error did not occur due to tbas vs. spaces. Both work as expected. The error suggests that there was a questionmark "?" in the first line (first-character)
