### ISSUE TITLE
fs.js:663   return binding.open(pathModule.toNamespacedPath(path)

### ISSUE THREAD

**Issue by le93us** [esdoc/esdoc#484]
Hello.

`kubuntu 17.10`, `node 9`
[bug demo git repo](https://github.com/le93us/esdoc-bug-demo)

I couldn't execute `esdoc` in the simplest example:
```
lex@acer:~/Desktop/esdoc$ yarn run esdoc
yarn run v1.3.2
warning package.json: No license field
$ /home/lex/Desktop/esdoc/node_modules/.bin/esdoc
parse: /home/lex/Desktop/esdoc/src/.external-ecmascript.js
parse: /home/lex/Desktop/esdoc/src/app.js
fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open './README.md'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Function._generateForIndex (/home/lex/Desktop/esdoc/node_modules/esdoc/out/src/ESDoc.js:253:44)
    at Function.generate (/home/lex/Desktop/esdoc/node_modules/esdoc/out/src/ESDoc.js:123:25)
    at ESDocCLI.exec (/home/lex/Desktop/esdoc/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/home/lex/Desktop/esdoc/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can anyone help?

**Comment by le93us** [comment]
after `esdoc` global installation
```
lex@acer:~/Desktop/esdoc$ esdoc
parse: /home/lex/Desktop/esdoc/src/.external-ecmascript.js
parse: /home/lex/Desktop/esdoc/src/app.js

TypeError: Cannot read property 'type' of undefined
    at Plugin._getParamsFromNode (/home/lex/Desktop/esdoc/node_modules/esdoc-lint-plugin/src/Plugin.js:54:18)
    at Plugin.onPublish (/home/lex/Desktop/esdoc/node_modules/esdoc-lint-plugin/src/Plugin.js:26:31)
    at Plugin._execHandler (/usr/lib/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onPublish (/usr/lib/node_modules/esdoc/out/src/Plugin/Plugin.js:154:10)
    at Function._publish (/usr/lib/node_modules/esdoc/out/src/ESDoc.js:354:24)
    at Function.generate (/usr/lib/node_modules/esdoc/out/src/ESDoc.js:149:10)
    at ESDocCLI.exec (/usr/lib/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/usr/lib/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
```

**Comment by le93us** [comment]
No response.

**Comment by le93us** [comment]
Authors had fixed the issue without messaging here (

Anyway, - thanks - now it works ok!

**Comment by le93us** [comment]
Bug is still actual.

**Comment by 22a** [comment]
Duplicate of https://github.com/esdoc/esdoc/issues/432
