### ISSUE TITLE
Unable to document object parameters

### ISSUE THREAD

**Issue by robertmain** [esdoc/esdoc#487]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [ ] https://esdoc.org/manual/feature.html
- [ ] https://esdoc.org/manual/config.html
- [X ] https://esdoc.org/manual/tags.html
- [ ] https://esdoc.org/manual/api.html
- [ ] https://esdoc.org/manual/faq.html

# Short summary of your issue
As things currently stand, it appears to be impossible to document object parameter properties. That is to say, if my method/function accepts an object with certain properties - it is not currently possible to document this, other than putting an object literal between the type braces.

Here's what I would hope to achieve:
```js

/**
 * Encode JPEG To Stream
 *
 * Encode the JPEG image to output stream
 *
 * @param {Number} img.width  Image width
 * @param {Number} img.height Image height
 * @param {Buffer} img.data   Raw buffer of JPEG data
 * @param {Stream} outstream  The stream to write the JPEG file to
 * @returns {Promise<void>}
 */
```

As a way to document what data and what types should be stored in the `img `parameter. However - currently this just results in esdoc bombing out with the error below

# Input data for reproducing
#### Configuration
```json
{
    "source":"./src",
    "destination":"./docs",
    "includes":[
        "\\.js$"
    ],
    "excludes":[
        "\\uint32.js$"
    ],
    "plugins":[
        {
            "name":"esdoc-standard-plugin",
            "option":{
                "lint":{
                    "enable":true
                },
                "coverage":{
                    "enable":true
                },
                "accessor":{
                    "access":[
                        "public",
                        "protected"
                    ],
                    "autoPrivate":true
                },
                "undocumentIdentifier":{
                    "enable":true
                },
                "unexportedIdentifier":{
                    "enable":false
                },
                "typeInference":{
                    "enable":true
                }
            }
        },
        {
            "name": "esdoc-node"
        },
        {
            "name": "esdoc-member-plugin"
        },
        {
            "name": "esdoc-integrate-test-plugin",
            "option": {
                "source": "./tests/unit/specs/",
                "interfaces": ["describe", "it"],
                "includes": ["(spec|test)\\.js$"],
                "excludes": ["\\.config\\.js$"]
            }
        }
    ]
}
```

#### Codes
```js
n/a
```

# Output data
#### Log
```

TypeError: Cannot read property 'length' of undefined
    at Plugin._formatResult (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc-lint-plugin\src\Plugin.js:140:65)
    at Plugin.onPublish (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc-lint-plugin\src\Plugin.js:33:26)
    at Plugin._execHandler (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\Plugin\Plugin.js:55:26)
    at Plugin.onPublish (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\Plugin\Plugin.js:154:10)
    at Function._publish (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDoc.js:354:24)
    at Function.generate (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDoc.js:149:10)
    at ESDocCLI.exec (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDocCLI.js:71:23)
    at Object.<anonymous> (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDocCLI.js:182:7)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pureimage@0.1.3 docs: `esdoc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pureimage@0.1.3 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robert\AppData\Roaming\npm-cache\_logs\2017-12-10T14_43_17_392Z-debug.log
```

#### Screen shot of documentation
// attach a image into here

# Exception output (if possible)
#### Log
```

TypeError: Cannot read property 'length' of undefined
    at Plugin._formatResult (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc-lint-plugin\src\Plugin.js:140:65)
    at Plugin.onPublish (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc-lint-plugin\src\Plugin.js:33:26)
    at Plugin._execHandler (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\Plugin\Plugin.js:55:26)
    at Plugin.onPublish (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\Plugin\Plugin.js:154:10)
    at Function._publish (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDoc.js:354:24)
    at Function.generate (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDoc.js:149:10)
    at ESDocCLI.exec (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDocCLI.js:71:23)
    at Object.<anonymous> (C:\Users\robert\Code\Node\node-pureimage\node_modules\esdoc\out\src\ESDocCLI.js:182:7)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pureimage@0.1.3 docs: `esdoc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pureimage@0.1.3 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robert\AppData\Roaming\npm-cache\_logs\2017-12-10T14_43_17_392Z-debug.log
```

#### Screen shot of documentation
// attach a image into here

# Your environment
- OS type and version: Windows 10
- Node.js version:  8.8.4
- ESDoc version:  1.0.4

**Comment by DrWilliamsSteven** [comment]
Similar to the way you can use @property <type> <name> [description] for properties on a return object.

**Comment by robertmain** [comment]
@drwilliamssteven how do you mean?

**Comment by DrWilliamsSteven** [comment]
You can do

```
/**
 * @desc This is a test function
 * @param {{foo: number, bar: string}} parameters - this is parameters
 * @param {number} parameters.foo - this is property param.
 * @param {string} parameters.bar - this is property param.

 */
export function myFunc({ foo, bar }: { foo: number, bar: string }) { return foo + bar; }

/**
 * @desc This is a test function
 * @param {Object} parameters - this is object param.
 * @param {number} parameters.foo - this is property param.
 * @param {string} parameters.bar - this is property param.
 */
export function myFunc2({ foo, bar }: { foo: number, bar: string }) { return foo + bar; }
```

**Comment by robertmain** [comment]
Is that not what I did though? See my code sample..
