### ISSUE TITLE
TypeError when generating docs | Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pixelass** [esdoc/esdoc#489]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)

- [x] https://esdoc.org/manual/feature.html
- [x] https://esdoc.org/manual/config.html
- [x] https://esdoc.org/manual/tags.html
- [x] https://esdoc.org/manual/api.html
- [x] https://esdoc.org/manual/faq.html

# Short summary of your issue

After esdoc ran I get an error

### Configuration
```json
{
  "destination": "./docs/api",
  "source": "./@stiligita/",
  "includes": ["\\.js$"],
  "excludes": ["__tests__", "examples", "webpack.*.*js"],
  "plugins": [{
    "name": "esdoc-ecmascript-proposal-plugin",
    "option": {
      "all": true
    }
  }, {
    "name": "esdoc-standard-plugin"
  }]
}

```

### Codesource

https://github.com/pixelass/stiligita/tree/master/%40stiligita

### Log
```
12:45 $ yarn docs
yarn run v1.3.2
$ esdoc
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/.external-ecmascript.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/constants/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/core/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/dom/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/dom/render.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/dom-elements/attributes.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/dom-elements/get-invalid-attributes.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/dom-elements/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/hash-code/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/react/dom-elements.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/react/get-invalid-attributes.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/react/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/store/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/stylesheets/css.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/stylesheets/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/stylesheets/keyframes.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/templates/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/utils/index.js
parse: /Users/greada/Documents/workspace/private/stiligita/@stiligita/vue/index.js

TypeError: Cannot read property 'length' of undefined
    at Plugin._formatResult (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc-lint-plugin/src/Plugin.js:140:65)
    at Plugin.onPublish (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc-lint-plugin/src/Plugin.js:33:26)
    at Plugin._execHandler (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onPublish (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc/out/src/Plugin/Plugin.js:154:10)
    at Function._publish (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc/out/src/ESDoc.js:354:24)
    at Function.generate (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc/out/src/ESDoc.js:149:10)
    at ESDocCLI.exec (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/Users/greada/Documents/workspace/private/stiligita/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Screen shot of documentation

<img width="1424" alt="screen shot 2017-12-12 at 12 46 24" src="https://user-images.githubusercontent.com/1148334/33883045-8afb6872-df3a-11e7-8888-f19ab334dbc9.png">

- OS type and version: OS X 10.12.6 (16G1036)
- Node.js version: 8.9.1
- ESDoc version: 1.0.4

**Comment by pixelass** [comment]
I also tried to disable lint (without success)

```
{
  "destination": "./docs/api",
  "source": "./@stiligita/",
  "includes": ["\\.js$"],
  "excludes": ["__tests__", "examples", "webpack.*.*js"],
  "plugins": [{
    "name": "esdoc-ecmascript-proposal-plugin",
    "option": {
      "all": true
    }
  }, {
    "name": "esdoc-standard-plugin",
    "options": {
      "lint": {
        "enable": false
      },
      "coverage": {
        "enable": false
      },
      "accessor": {
        "access": [
          "public",
          "protected",
          "private"
        ],
        "autoPrivate": true
      }
    }
  }]
}
```

**Comment by pixelass** [comment]
Seems to be another issue due to missing debug or verbose option:


ERRORS NEED BETTER LOGS.

We need a better logging. Right now it is impossible to find errors without having to read documentations line by line.

**Comment by pixelass** [comment]
Issue is resolve but contains valid subissues:

can't disble lint:
https://github.com/esdoc/esdoc/issues/489#issuecomment-351040006

keeping open for now.

**Comment by ericblade** [comment]
@pixelass it seems that you should use "option" not "options".

I'm running into a couple of totally random crashes and had to figure that out too. :-)

**Comment by pixelass** [comment]
@ericblade thanks for the comment. I didn't notice the typo. As mentioned my issue was resolved by fixing linting issues by carefully reviewing each docblock. My last comment mentioned that I was not able to disable lint.

**Comment by ericblade** [comment]
right. i think there should be a topic to discuss how difficult it is to find errors in the linting process.  i've just disabled the linting completely, because i'm not going to chase through all the jsdoc strings to see if i can figure out what piece of what is breaking it.

**Comment by pixelass** [comment]
Closing this since I lost trust in this project and @h13i32maru 

I might just fork esdoc since this behaviour is ridiculous.
