### ISSUE TITLE
SyntaxError: Invalid regular expression: /[~]{( Set$/: Unterminated group

### ISSUE THREAD

**Issue by jy95** [esdoc/esdoc#497]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/feature.html
- [x] https://esdoc.org/manual/config.html
- [x] https://esdoc.org/manual/tags.html
- [x] https://esdoc.org/manual/api.html
- [x] https://esdoc.org/manual/faq.html

# Short summary of your issue

Hello, I want to convert my old jsdoc code to esdoc but I got this error. Any ideas why/ how to fix it ?
The tested repository : https://github.com/jy95/torrent-files-library/tree/docs-esdoc

# Input data for reproducing
#### Configuration
```json
{
  "source": "./src",
  "destination": "./docs",
  "plugins": [
    {"name": "esdoc-standard-plugin",
      "option": {
        "test": {
          "source": "./test/",
          "interfaces": ["test"],
          "excludes": ["_constants.js"]
        }
      }
    },
    {"name": "esdoc-ecmascript-proposal-plugin", "option": {"all": true}}
  ]
}
```

#### Codes
```js
// In the file `src/jsdoc/types.js` I declare new types , just to not make my source code not to verbose ^^

/**
 * The result of parsing file name
 * @typedef {Object} TPN
 * @see {@link https://github.com/clement-escolano/parse-torrent-title}
 * @property {(string)} title - The file title
 * @property {(number)} [season] - The season number
 * @property {(number)} [episode] - The episode number
 * @property {(number)} [year] - The year
 * @property {(string)} [resolution] - The resolution
 * @property {(string)} [codec] - The codec
 * @property {(string)} [audio] - The audio
 * @property {(string)} [group] - The group that releases this file
 * @property {(string)} [region] - The region
 * @property {(string)} [container] - The container
 * @property {(string)} [language] - The file language
 * @property {(boolean)} [extended] - extended ?
 * @property {(boolean)} [unrated] - unrated ?
 * @property {(boolean)} [proper] - proper ?
 * @property {(boolean)} [repack] - repack ?
 * @property {(boolean)} [convert] - convert ?
 * @property {(boolean)} [hardcoded] - hardcoded ?
 * @property {(boolean)} [retail] - retail ?
 * @property {(boolean)} [remastered] - remastered ?
 * @property {(string)} [source] - the source
 */

/**
 * The extended TPN object
 * @typedef {TPN} TPN_Extended
 * @property {string} filePath - additionnal property useful for this library
 */

/**
  * @typedef {Map<string, {( Set<TPN_Extended>| Map<string,Set<TPN_Extended>> )}>} StoreVar
*/


// In the file `src/TorrentLibrary.js` I use this typedef like these two examples :
/**
  * @type {Set<TPN_Extended>}
  * @type {Map<string, Set<TPN_Extended>>}
*/
```

# Output data
#### Log
```
parse: D:\workspaceNodeJs\torrent-files-library\src\.external-ecmascript.js
parse: D:\workspaceNodeJs\torrent-files-library\src\docs\events.js
parse: D:\workspaceNodeJs\torrent-files-library\src\docs\types.js
parse: D:\workspaceNodeJs\torrent-files-library\src\filters\filterBooleanProperty.js
parse: D:\workspaceNodeJs\torrent-files-library\src\filters\filterNumberProperty.js
parse: D:\workspaceNodeJs\torrent-files-library\src\filters\filterStringProperty.js
parse: D:\workspaceNodeJs\torrent-files-library\src\TorrentLibrary.js
output: D:\workspaceNodeJs\torrent-files-library\docs\lint.json
output: D:\workspaceNodeJs\torrent-files-library\docs\coverage.json
output: D:\workspaceNodeJs\torrent-files-library\docs\badge.svg
output: D:\workspaceNodeJs\torrent-files-library\docs\image\github.png
resolve: extends chain
resolve: necessary
resolve: ignore
resolve: link
resolve: markdown in description
resolve: test relation

SyntaxError: Invalid regular expression: /[~]{( Set$/: Unterminated group
    at new RegExp (<anonymous>)
    at IdentifiersDocBuilder._findByName (D:\workspaceNodeJs\torrent-files-library\node_modules\esdoc-publish-html-plugin\out\src\Builder\DocBuilder.js:116:20)
    at IdentifiersDocBuilder._buildDocLinkHTML (D:\workspaceNodeJs\torrent-files-library\node_modules\esdoc-publish-html-plugin\out\src\Builder\DocBuilder.js:768:22)
    at IdentifiersDocBuilder._buildTypeDocLinkHTML (D:\workspaceNodeJs\torrent-files-library\node_modules\esdoc-publish-html-plugin\out\src\Builder\DocBuilder.js:733:28)
    at v.split.map.vv (D:\workspaceNodeJs\torrent-files-library\node_modules\esdoc-publish-html-plugin\out\src\Builder\DocBuilder.js:729:23)
    at Array.map (<anonymous>)
    at inner.split.map.v (D:\workspaceNodeJs\torrent-files-library\node_modules\esdoc-publish-html-plugin\out\src\Builder\DocBuilder.js:727:29)
    at Array.map (<anonymous>)
    at IdentifiersDocBuilder._buildTypeDocLinkHTML (D:\workspaceNodeJs\torrent-files-library\node_modules\esdoc-publish-html-plugin\out\src\Builder\DocBuilder.js:726:43)
    at IdentifiersDocBuilder._buildSignatureHTML (D:\workspaceNodeJs\torrent-files-library\node_modules\esdoc-publish-html-plugin\out\src\Builder\DocBuilder.js:854:34)
```

#### Screen shot of documentation
No docs generated

# Your environment
- OS type and version: Windows 10 Build 1709
- Node.js version: 8.9.3
- ESDoc version: 1.0.4

**Comment by jy95** [comment]
The cause is the declaration of this : 
```js
/**
 *@typedef {Map<string, {( Set<TPN_Extended>| Map<string,Set<TPN_Extended>> )}>} StoreVar
*/
```

Currently, the only way to fix it is to break this declaration into two separate typedef like this : 
```js
/**
 * @typedef {Set<TPN_Extended>| Map<string,Set<TPN_Extended>} StorageVar
 */

/**
 *@typedef {Map<string, StorageVar>} StoreVar
*/
```js
