### ISSUE TITLE
Esdoc is failing

### ISSUE THREAD

**Issue by ivikash** [esdoc/esdoc#498]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/feature.html
- [x] https://esdoc.org/manual/config.html
- [x] https://esdoc.org/manual/tags.html
- [x] https://esdoc.org/manual/api.html
- [x] https://esdoc.org/manual/faq.html

# Short summary of your issue
I am trying to use esdoc for a React Project. ESDoc is failing with `
TypeError: Cannot read property 'length' of undefined`

# Input data for reproducing
#### Configuration
```json
{
  "source": "./src",
  "destination": "./docs",
  "plugins": [
    {"name": "esdoc-standard-plugin"},
    {"name": "esdoc-jsx-plugin", "option": {"enable": true}}
  ]
}
```

#### Codes
```js
/**
 * Generate array of a given length
 * @param {Number} number of items in the array
 * @return {Array} array of given length n
 */
const generateArray = n => Array.from(Array(n).keys());

/**
 * Serialize object for URL params
 *
 * Input
 * -----
 *
 * {
 *    station: "XYZ",
 *    week: 4
 * }
 *
 * Output
 * ------
 * "station=xyz&week=4"
 *
 * @param {Object} RequestParams
 * @param {String} delimiterBetweenObjects This is the delimiter used to join each key value pair
 * @param {String} delimiterBetweenItems This is the delimiter used to join individual objects while serializations
 * @return {String} returns string joined with delimiter
 */

const getSerializedObject = (params, delimiterBetweenObjects = '=', delimiterBetweenItems = '&') =>
  Object.entries(params)
    .map(i => i.join(delimiterBetweenObjects))
    .join(delimiterBetweenItems);

export { generateArray, getSerializedObject };

```

# Output data
#### Log
```
TypeError: Cannot read property 'length' of undefined
    at Plugin._formatResult (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc-lint-plugin/src/Plugin.js:140:65)
    at Plugin.onPublish (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc-lint-plugin/src/Plugin.js:33:26)
    at Plugin._execHandler (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onPublish (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc/out/src/Plugin/Plugin.js:154:10)
    at Function._publish (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc/out/src/ESDoc.js:354:24)
    at Function.generate (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc/out/src/ESDoc.js:149:10)
    at ESDocCLI.exec (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/Users/vikasagr/.nvm/versions/node/v9.2.0/lib/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
```
#### Screen shot of documentation
<img width="1038" alt="screen shot 2018-01-30 at 9 36 26 pm" src="https://user-images.githubusercontent.com/371007/35576938-50aa7f76-0606-11e8-81d7-c52c9a0a3335.png">

# Your environment
- OS type and version: 
```
λ sw_vers
ProductName:	Mac OS X - Sierra
ProductVersion:	10.12.6
BuildVersion:	16G1212
```
- Node.js version: v9.2.0
- ESDoc version: 1.0.4

**Comment by ivikash** [comment]
Seems like disabling esdoc-lint-plugin is the only solution. Can you tell me a better way to fix this?

**Comment by TriMoon** [comment]
duplicate of #403  ?

**Comment by ivikash** [comment]
Yes
