### ISSUE TITLE
Unexpected token at position 0

### ISSUE THREAD

**Issue by lxsmnsyc** [esdoc/esdoc#517]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [ ] https://esdoc.org/manual/feature.html
- [ ] https://esdoc.org/manual/config.html
- [ ] https://esdoc.org/manual/tags.html
- [ ] https://esdoc.org/manual/api.html
- [ ] https://esdoc.org/manual/faq.html

# Short summary of your issue
```bash
undefined:1
ï¿½ï¿½{
^

SyntaxError: Unexpected token ï¿½ in JSON at position 0
```
# Input data for reproducing
#### Configuration
```json
{
    "source": "./src",
    "destination": "./docs",
    "plugins": [{ "name": "esdoc-standard-plugin" }]
}
```

#### Codes
I just followed the steps from the README.md
```bash
cd vector
npm install --save-dev esdoc esdoc-standard-plugin
echo '{
  "source": "./src",
  "destination": "./docs",
  "plugins": [{"name": "esdoc-standard-plugin"}]
}' > .esdoc.json
./node_modules/.bin/esdoc
```

# Output data
#### Log
```
// write into here
```

#### Screen shot of documentation
// attach a image into here

# Exception output (if possible)
#### Log
```bash
$ ./node_modules/.bin/esdoc
undefined:1
ï¿½ï¿½{
^

SyntaxError: Unexpected token ï¿½ in JSON at position 0
    at JSON.parse (<anonymous>)
    at ESDocCLI._createConfigFromJSONFile (C:\Users\Alexis\Desktop\ui designs\vector\node_modules\esdoc\out\src\ESDocCLI.js:153:27)
    at ESDocCLI.exec (C:\Users\Alexis\Desktop\ui designs\vector\node_modules\esdoc\out\src\ESDocCLI.js:65:21)
    at Object.<anonymous> (C:\Users\Alexis\Desktop\ui designs\vector\node_modules\esdoc\out\src\ESDocCLI.js:182:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

```

#### Screen shot of documentation
// attach a image into here

# Your environment
- OS type and version: Win 10 1803 build 17134.112
- Node.js version: v8.11.3
- ESDoc version: current

**Comment by lxsmnsyc** [comment]
I've already checked issues [#477](https://github.com/esdoc/esdoc/issues/477) and [#369](https://github.com/esdoc/esdoc/issues/369) but it doesn't help me with my problem

**Comment by MilesYu15** [comment]
I have the same problem. The problem may be the encoding of the esdoc.json file. Mine was UTF-16 at first. I created a new one in UTF-8, and the problem disappeared. I hope this can help you!

**Comment by jonasexplore** [comment]
> I have the same problem. The problem may be the encoding of the esdoc.json file. Mine was UTF-16 at first. I created a new one in UTF-8, and the problem disappeared. I hope this can help you!

I'd change to UTF-8 and worked! Thanks so much ^^.

**Comment by f-mtz** [comment]
@fallying that did work, thank you
