### ISSUE TITLE
Esdoc fails upon object destructuring assignment with quoted keys

### ISSUE THREAD

**Issue by danyfedorov** [esdoc/esdoc#519]
# Short summary of your issue
If a variable is declared like this (with quoted field)
``` js
const { 'a-name': anotherName } = { 'a-name': 123 };
```
esdoc fails.

# Input data for reproducing
See this repo https://github.com/bugdie4k/esdoc-fail-example.  
You can clone it and then do the following to reproduce:
```
$ npm i
$ ./run-esdoc.sh 
```
#### Configuration
```json
{
    "source": ".",
    "destination": "./docs",
    "excludes": ["node_modules"],
    "plugins": [{
            "name": "esdoc-standard-plugin",
        }        
    ]
}
```

# Exception output (if possible)
#### Log
```
parse: /home/dfedorov/._p/esdoc-fail-example/.external-ecmascript.js
parse: /home/dfedorov/._p/esdoc-fail-example/index.js
warning: ./README.md is not found. Please check config.index.
/home/dfedorov/._p/esdoc-fail-example/node_modules/esdoc-accessor-plugin/src/Plugin.js:16
        if (autoPrivate && doc.name.charAt(0) === '_') {
                                   ^

TypeError: Cannot read property 'charAt' of undefined
    at Plugin.onHandleDocs (/home/dfedorov/._p/esdoc-fail-example/node_modules/esdoc-accessor-plugin/src/Plugin.js:16:36)
    at Plugin._execHandler (/home/dfedorov/._p/esdoc-fail-example/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onHandleDocs (/home/dfedorov/._p/esdoc-fail-example/node_modules/esdoc/out/src/Plugin/Plugin.js:135:10)
    at Function.generate (/home/dfedorov/._p/esdoc-fail-example/node_modules/esdoc/out/src/ESDoc.js:132:32)
    at ESDocCLI.exec (/home/dfedorov/._p/esdoc-fail-example/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/home/dfedorov/._p/esdoc-fail-example/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

```

# Your environment
- OS type and version: Ubuntu 16.04
- Node.js version: 6.3.0 (also checked with 8.11.3)
- ESDoc version: 1.1.0

**Comment by alexdiliberto** [comment]
Just ran into this today as well except I was using a quoted class field which is a valid syntax; however, breaks ESDoc

```js
export default class MyClass {
  /* some prop */
  'my-prop' = 123;
}
```

**Comment by Lakitna** [comment]
Me too, but with a quoted export value which is also valid js syntax.

```js
exports['date-time'] = function() {
}
```

**Comment by RossComputerGuy** [comment]
Similar error, possibly related:
```
/home/ross/emberliteOS/core/node_modules/esdoc/out/src/Parser/CommentParser.js:49
        if (nextLine.charAt(0) === '@') {
                     ^

TypeError: Cannot read property 'charAt' of undefined
    at Function.parse (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/Parser/CommentParser.js:49:22)
    at DocFactory._traverseComments (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/Factory/DocFactory.js:393:44)
    at new DocFactory (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/Factory/DocFactory.js:99:28)
    at Function._traverse (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/ESDoc.js:233:21)
    at /home/ross/emberliteOS/core/node_modules/esdoc/out/src/ESDoc.js:112:25
    at Function._walk (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/ESDoc.js:204:9)
    at Function.generate (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/ESDoc.js:96:10)
    at ESDocCLI.exec (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/home/ross/emberliteOS/core/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
```

Caused by this comment:
```js
/**
 * @external {EventEmitter} https://manual.os-js.org/api/osjs-event-emitter/class/osjs-event-emitter/index.js~EventEmitter.html
 * @module @osjs/event-emitter
 */
```
