### ISSUE TITLE
problem with babel@7 support (maybe)

### ISSUE THREAD

**Issue by SilentImp** [esdoc/esdoc#522]
# Short summary of your issue

> jsdoctor "./source/**/*.js"
> (node:55995) UnhandledPromiseRejectionWarning: Error: /bin/bash: line 0: globstar: invalid shell option name
>     at handleError (/Users/silentimp/.nvm/versions/node/v9.11.2/lib/node_modules/jsdoctor/node_modules/bash-glob/index.js:328:11)
>     at Socket.<anonymous> (/Users/silentimp/.nvm/versions/node/v9.11.2/lib/node_modules/jsdoctor/node_modules/bash-glob/index.js:257:10)
>     at Socket.emit (events.js:180:13)
>     at addChunk (_stream_readable.js:274:12)
>     at readableAddChunk (_stream_readable.js:261:11)
>     at Socket.Readable.push (_stream_readable.js:218:10)
>     at Pipe.onread (net.js:581:20)
> (node:55995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:55995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# Input data for reproducing
#### Configuration
noconfig

#### Codes
can't add whole project

# Output data
it already present at the begining

#### Screen shot of documentation
// attach a image into here

# Exception output (if possible)
#### Log
> (node:55995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

#### Screen shot of documentation
none was generated

# Your environment
- OS type and version: macosx 10.13.6
- Node.js version: v9.11.2
- ESDoc version: 1.0.0

**Comment by vihanb** [comment]
Are you using any syntax that _only_ babel 7 supports? Though error looks like your shell is doing something to the glob. What is exact command you are running?
