### ISSUE TITLE
Crash "TypeError: Cannot read property 'charAt' of null"

### ISSUE THREAD

**Issue by lll000111** [esdoc/esdoc#535]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [ ] https://esdoc.org/manual/feature.html
- [ ] https://esdoc.org/manual/config.html
- [ ] https://esdoc.org/manual/tags.html
- [ ] https://esdoc.org/manual/api.html
- [ ] https://esdoc.org/manual/faq.html

Bug

# Short summary of your issue

Crash running `./node_modules/.bin/esdoc`

# Input data for reproducing
#### Configuration
```json
{
  "source": "./src",
  "destination": "./docs",
  "plugins": [
    {"name": "esdoc-standard-plugin"},
    {"name": "esdoc-flow-type-plugin", "option": {"enable": true}}
  ]
}
```

#### Codes
```js
// write into here
```

I don't have any specific code that produces the issue &mdash; the last file shown before the crash does not seem to cause it, I emptied that file completely and still got the error. Seems to be cumulative, **after parsing**, and I have no idea which of the many files is to blame because there is no usable debug information that could give me a hint apart from the crash.

# Output data
#### Log
```
/home/mha/one/node_modules/esdoc-accessor-plugin/src/Plugin.js:16
        if (autoPrivate && doc.name.charAt(0) === '_') {
                                    ^

TypeError: Cannot read property 'charAt' of null
    at Plugin.onHandleDocs (/home/mha/one/node_modules/esdoc-accessor-plugin/src/Plugin.js:16:37)
    at Plugin._execHandler (/home/mha/one/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onHandleDocs (/home/mha/one/node_modules/esdoc/out/src/Plugin/Plugin.js:135:10)
    at Function.generate (/home/mha/one/node_modules/esdoc/out/src/ESDoc.js:132:32)
    at ESDocCLI.exec (/home/mha/one/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/home/mha/one/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
```

# Your environment
- OS type and version: Linux Mint
- Node.js version: 11.5.0
- ESDoc version: 1.1.0

**Comment by lll000111** [comment]
The crash does not happen when I set standard plugin option `"autoPrivate": false` (default is `true`)

**Comment by ericblade** [comment]
Can confirm, setting autoPrivate: false prevents this error from occuring.

**Comment by DanielRuf** [comment]
See https://github.com/esdoc/esdoc-plugins/pull/91
