### ISSUE TITLE
Can't create documentation when using @jest-env

### ISSUE THREAD

**Issue by DamickDoni** [esdoc/esdoc#548]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/feature.html
- [x] https://esdoc.org/manual/config.html
- [x] https://esdoc.org/manual/tags.html
- [x] https://esdoc.org/manual/api.html
- [x] https://esdoc.org/manual/faq.html

# Short summary of your issue
When using a jest test with jsdom as test-enviroment (`@jest-enviroment`), the documentation cannot be created.

# Input data for reproducing
#### Configuration
```json
{
            "name": "esdoc-standard-plugin",
            "option": {
                "test": {
                    "source": "./src",
                    "interfaces": [
                        "describe",
                        "it",
                        "context",
                        "suite",
                        "test"
                    ],
                    "includes": ["(spec|Spec|test|Test)\\.ts$"]
                },
..
```

#### Codes
```ts
/**
 * @jest-environment jsdom
 */
import 'whatwg-fetch';

describe('request', () => {
    beforeEach(() => {
        window.fetch = jest.fn();
    });
...
```

# Output data
#### Log
```
{ SyntaxError: Unexpected token (18:13)
    at Parser.pp$5.raise (/src/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/src/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/src/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/src/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/src/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/src/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/src/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/src/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/src/node_modules/babylon/lib/index.js:3828:26)
    at Parser.pp$3.parseExprAtom (/src/node_modules/babylon/lib/index.js:3709:19) pos: 480, loc: Position { line: 18, column: 13 } }
/src/node_modules/esdoc/out/src/Factory/DocFactory.js:135
    for (const exportNode of this._ast.program.body) {
                                       ^

TypeError: Cannot read property 'program' of undefined
    at DocFactory._inspectExportDefaultDeclaration (/src/node_modules/esdoc/out/src/Factory/DocFactory.js:135:40)
    at new DocFactory (/src/node_modules/esdoc/out/src/Factory/DocFactory.js:90:10)
    at Function._traverse (/src/node_modules/esdoc/out/src/ESDoc.js:233:21)
    at _walk.filePath (/src/node_modules/esdoc/out/src/ESDoc.js:112:25)
    at Function._walk (/src/node_modules/esdoc/out/src/ESDoc.js:204:9)
    at Function._walk (/src/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function._walk (/src/node_modules/esdoc/out/src/ESDoc.js:206:14)
    at Function.generate (/src/node_modules/esdoc/out/src/ESDoc.js:96:10)
    at ESDocCLI.exec (/src/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/src/node_modules/esdoc/out/src/ESDocCLI.js:182:7)

```

# Your environment
- OS type and version: Ubuntu 16.
- Node.js version: 10.16.0
- ESDoc version: 1.1.0

**Comment by mstruensee** [comment]
why would you want docs generated for test files, just exclude them...
```
	excludes: [
		"\\.test\\.js$",
	],
```

^^ what I do ...
