### ISSUE TITLE
Cannot read property 'program' of undefined

### ISSUE THREAD

**Issue by Exlord** [esdoc/esdoc#568]
`.\node_modules\.bin\esdoc -c .esdoc.json`

```
{
  "source": "./src",
  "destination": "./docs",
  "plugins": [
    {
      "name": "esdoc-standard-plugin"
    },
    {
      "name": "esdoc-typescript-plugin",
      "option": {
        "enable": true
      }
    }
  ],
  "excludes": [".*node_modules.*", "\\.spec\\.js", "^build/.*"]
}
```

```
SyntaxError: Unexpected token (77:37)
    at Parser.pp$5.raise (X\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (X\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseIdentifier (X\node_modules\babylon\lib\index.js:4332:10)
    at Parser.pp$3.parsePropertyName (X\node_modules\babylon\lib\index.js:4156:96)
    at Parser.pp$3.parseObj (X\node_modules\babylon\lib\index.js:4045:12)
    at Parser.pp$2.parseBindingAtom (X\node_modules\babylon\lib\index.js:3087:19)
    at Parser.pp$1.parseVarHead (X\node_modules\babylon\lib\index.js:2355:18)
    at Parser.pp$1.parseVar (X\node_modules\babylon\lib\index.js:2338:10)
    at Parser.pp$1.parseVarStatement (X\node_modules\babylon\lib\index.js:2169:8)
    at Parser.pp$1.parseStatement (X\node_modules\babylon\lib\index.js:1861:19) {
  pos: 1860,
  loc: Position { line: 77, column: 37 }
}
X\node_modules\esdoc\out\src\Factory\DocFactory.js:135
    for (const exportNode of this._ast.program.body) {
                                       ^

TypeError: Cannot read property 'program' of undefined
    at DocFactory._inspectExportDefaultDeclaration (X\node_modules\esdoc\out\src\Factory\DocFactory.js:135:40)
    at new DocFactory (X\node_modules\esdoc\out\src\Factory\DocFactory.js:90:10)
    at Function._traverse (X\node_modules\esdoc\out\src\ESDoc.js:233:21)
    at X\node_modules\esdoc\out\src\ESDoc.js:112:25
    at Function._walk (X\node_modules\esdoc\out\src\ESDoc.js:204:9)
    at Function._walk (X\node_modules\esdoc\out\src\ESDoc.js:206:14)
    at Function._walk (X\node_modules\esdoc\out\src\ESDoc.js:206:14)
    at Function._walk (X\node_modules\esdoc\out\src\ESDoc.js:206:14)
    at Function.generate (X\node_modules\esdoc\out\src\ESDoc.js:96:10)
    at ESDocCLI.exec (X\node_modules\esdoc\out\src\ESDocCLI.js:71:23)
```

# Your environment
- Win 10 X64
- Node.js version: 14.15.0
- ESDoc version: 1.1.0

**Comment by bachu-shannon** [comment]
I have a similar problem!
