### ISSUE TITLE
Having trouble identifying errors again

### ISSUE THREAD

**Issue by benderTheCrime** [esdoc/esdoc#63]
In a very similar fashion to the issue found here https://github.com/esdoc/esdoc/issues/11, I cannot generate documentation using the following repo: https://github.com/benderTheCrime/angie-injector

```bash
/usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:401
            throw _iteratorError5;
                  ^
TypeError: Cannot read property 'type' of null
    at Function.findVariableDeclarationAndNewExpressionNode (/usr/local/lib/node_modules/esdoc/out/src/Util/ASTUtil.js:133:79)
    at DocFactory._inspectExportDefaultDeclaration (/usr/local/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:166:56)
    at new DocFactory (/usr/local/lib/node_modules/esdoc/out/src/Factory/DocFactory.js:91:10)
    at Function._traverse (/usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:431:21)
    at /usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:183:26
    at Function._walk (/usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:386:13)
    at Function._walk (/usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:388:18)
    at Function.generate (/usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:125:12)
    at ESDocCLI.exec (/usr/local/lib/node_modules/esdoc/out/src/ESDocCLI.js:88:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/esdoc/out/src/ESDocCLI.js:142:7)
```

There is a gulp command `gulp esdoc` which does the trick in many other repos, but not this one. A simple `esdoc -c esdoc.json` also fails.

It would be preferable to know what the issue was exactly so that I could debug on my own (open source developers of all kinds prefer explicit error handling). This appears to happen for any number of reasons including, but not limited to:
* Parameter mismatch and restructuring
* Exports
* Unnamed functions
I toyed around a bit, but only after commenting out my exports was I able to get the esdoc task running. The exports seem to be syntactically correct.

**Comment by h13i32maru** [comment]
@benderTheCrime Hi! Thanks for this issue!
I published ESDoc v0.2.4 that fixed [the same issue](https://github.com/esdoc/esdoc/issues/60). Please try to use it.
