### ISSUE TITLE
Destructuring object cause error

### ISSUE THREAD

**Issue by apolkingg8** [esdoc/esdoc#65]
It's fine:
```js
import Foo from '../Foo'

//let {Foo1, Foo2, Foo3} = Foo

class Bar {
    yo() {

    }
}

export default Bar
```
but it's cause error:
```js
import Foo from '../Foo'

let {Foo1, Foo2, Foo3} = Foo

class Bar {
    yo() {

    }
}

export default Bar
```
error msg:
```
$ esdoc -c esdoc.json
/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:121
          if (autoPrivate && this.name.charAt(0) === '_') {
                                      ^
TypeError: Cannot read property 'charAt' of undefined
    at Object.<anonymous> (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:121:39)
    at /Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/node_modules/taffydb/taffy.js:743:17
    at each (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/node_modules/taffydb/taffy.js:126:17)
    at Object.<anonymous> (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/node_modules/taffydb/taffy.js:740:7)
    at Object.API.(anonymous function) [as update] (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/node_modules/taffydb/taffy.js:166:18)
    at DocResolver._resolveAccess (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:119:20)
    at DocResolver.resolve (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:51:12)
    at CoverageBuilder.DocBuilder (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:57:42)
    at new CoverageBuilder (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/out/src/Publisher/Builder/CoverageBuilder.js:33:81)
    at publish (/Users/applesw2/.nvm/versions/node/v0.12.2/lib/node_modules/esdoc/out/src/Publisher/publish.js:127:35)
```

**Comment by h13i32maru** [comment]
@apolkingg8 Hi! Thanks for this issue!
This is ESDoc bug :sweat: I will try to fix it. Please wait a little.

**Comment by apolkingg8** [comment]
Thanks you! I'll stay tuned for good news :+1:

**Comment by h13i32maru** [comment]
I published ESDoc v0.2.5. Please use it.

**Comment by apolkingg8** [comment]
It works like charm! Thanks for this awesome project! :beer:

**Comment by h13i32maru** [comment]
:+1:
