### ISSUE TITLE
Iterator methods crash the document generation

### ISSUE THREAD

**Issue by ralf-o** [esdoc/esdoc#73]
esdoc version: 0.2.5

Classes with iterator methods (=> Symbol.iterator/@@iterator) crash the documentation generation process:

class MyIterable {
    \[Symbol.iterator\]() { ... }
}

will cause the following error:

TypeError: Cannot call method 'charAt' of undefined
    at Object.<anonymous> (./node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:121:40)
    at ./node_modules/esdoc/node_modules/taffydb/taffy.js:743:17
    at each (./node_modules/esdoc/node_modules/taffydb/taffy.js:126:17)
    at Object.API.extend.that (./node_modules/esdoc/node_modules/taffydb/taffy.js:740:7)
    at Object.API.(anonymous function) [as update] (./node_modules/esdoc/node_modules/taffydb/taffy.js:166:18)
    at DocResolver._resolveAccess (./node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:119:20)
    at DocResolver.resolve (./node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:51:12)
    at CoverageBuilder.DocBuilder (./node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:57:42)
    at new CoverageBuilder (./node_modules/esdoc/out/src/Publisher/Builder/CoverageBuilder.js:33:81)
    at publish (./node_modules/esdoc/out/src/Publisher/publish.js:156:35)

Using "@ignore" as a workaround does not work.
Using flag "autoPrivate=false" works, but in the API documentation the '@@iterator' method is called 'undefined'.

**Comment by h13i32maru** [comment]
@ralf-o Hi! Thanks for this issue!
Sorry, this is ESDoc bug :sweat: I try to fix it and please wait a little.

**Comment by h13i32maru** [comment]
I published v0.2.6 that fixed this issue. Please try to use it.

**Comment by ralf-o** [comment]
I've tested the new version -> works great .... thanks a lot :-)
