### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by balupton** [esdoc/esdoc#79]
```
$ npm i esdoc
npm WARN prefer global marked@0.3.5 should be installed with -g

> fsevents@0.3.8 install /Users/balupton/Projects/focus/assert-helpers/node_modules/fsevents
> node-gyp rebuild

gyp: /Users/balupton/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/balupton/Projects/focus/assert-helpers/node_modules/fsevents) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/balupton/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/balupton/.nvm/versions/node/v4.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/balupton/Projects/focus/assert-helpers/node_modules/fsevents
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN install:fsevents fsevents@0.3.8 install: `node-gyp rebuild`
npm WARN install:fsevents Exit status 1
assert-helpers@2.0.0 /Users/balupton/Projects/focus/assert-helpers
├── esdoc@0.2.5  extraneous
└─┬ eslint@1.3.1
  └── espree@2.2.4 

npm WARN EPACKAGEJSON assert-helpers@2.0.0 license should be a valid SPDX license expression
```

**Comment by balupton** [comment]
seems to be an issue on my side, tried in a new directory and worked fine
