### ISSUE TITLE
"Invalid regular expression" in esdoc/node_modules/core-js/modules/es6.regexp.js:22:76

### ISSUE THREAD

**Issue by jdfreder** [esdoc/esdoc#89]
I don't know if this is a problem with esdoc or esdoc's usage of core-js or core-js itself.  Ran into this problem while trying to process some ES6, which is babel compatible.

```
> esdoc -c esdoc.json

badge.svg
identifiers.html
index.html
class/src/CodeMirror/input-model.js~CodeMirrorInputModel.html
class/src/cursor-model.js~CoordinateModel.html
class/src/cursor-model.js~CursorModel.html
class/src/input-model.js~InputModel.html
/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/ClassDocBuilder.js:79
            throw _iteratorError;
            ^

SyntaxError: Invalid regular expression: /[~]\object)=>void$/: Unmatched ')'
    at RegExp (native)
    at new RegExp (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/node_modules/core-js/modules/es6.regexp.js:22:76)
    at ClassDocBuilder._findByName (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:119:20)
    at ClassDocBuilder._buildDocLinkHTML (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:967:22)
    at ClassDocBuilder._buildTypeDocLinkHTML (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:943:21)
    at ClassDocBuilder._buildSignatureHTML (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:1076:33)
    at /home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:469:38
    at IceCap.loop (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/node_modules/ice-cap/out/src/IceCap.js:319:15)
    at ClassDocBuilder._buildSummaryDoc (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:466:11)
    at ClassDocBuilder._buildSummaryHTML (/home/jon/jupyter/jupyter-js-input-area/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:425:29)
```

**Comment by h13i32maru** [comment]
@jdfreder Hi! Thanks for this issue!
Please tell me the repository URL or minimum source code. I want to reproduce in my environment.

**Comment by jdfreder** [comment]
Hi @h13i32maru !  Thank you for the quick response.  I was trying to use it for this repository: https://github.com/jdfreder/jupyter-js-input-area/tree/initialdesign

**Comment by h13i32maru** [comment]
@jdfreder ``@param`` syntax in your repository is not valid.
https://github.com/jdfreder/jupyter-js-input-area/blob/initialdesign/src/model.js#L69-L70

Please be modified as follows.
- ``@param  {()=>object} getter`` => ``@param {function(): object} getter``
- ``@param  {(object)=>void} setter`` => ``@param {function(value: object)} setter``

And the repository has some invalid syntax.
- ``@param {[string]} foo`` => ``@param {string} [foo]``
- ``@param {any} foo`` => ``@param {*} foo``

Please see https://esdoc.org/tags.html#type-syntax for more information.

**Comment by jdfreder** [comment]
Thanks @h13i32maru !  Sorry for the noise.  I'll go ahead and correct all of those and ping back if I'm still having trouble.

**Comment by h13i32maru** [comment]
:+1:

**Comment by rhys-vdw** [comment]
Hey @h13i32maru, I'm having this issue as well. I think the real problem here is that the error gives no feedback about which file contains the syntax error. Is it possible for this to be wrapped with an error that lists file/line number or some more information about where the problem is?
